### ISSUE TITLE
Stop creating empty JS files

### ISSUE THREAD

**Issue by psb** [melange-re/melange#1048]
When creating a library Melange will create an empty JS file with the same name as that library (unless there is Reason file with the same name as the library), which has the contents:
```
// Generated by Melange
/* This output is empty. Its source's type definitions, externals and/or unused code got optimized away. */
```
Often these empty JS files can be safely ignored; however, they do add noise and can sometimes cause an app to crash. For example, I'm migrating a TS React app to ReasonReact and there is a folder called `auth`, and inside `auth` there is a TS file called `auth.ts`. One of the first steps I do when migrating an app to Reason is to add a Dune file to each folder to create a library, glob all the TS and TSX files as part of that library, and make sure the app is working as it should be. However, if the library is called `auth` in the Dune file then an empty `auth.js` file will be created and put next to the globbed `auth.ts` file. This will cause the app to crash as it preferentially loads the empty JS file over the TS file.

This can be easily prevented by renaming the library in the Dune. But there could be a situation where an empty JS file has the same name as an essential framework file, gets loaded by accident, and causes the app to crash.

**Comment by anmonteiro** [comment]
> This can be easily prevented by renaming the library in the Dune.

or adding `(wrapped false)`, I suppose. Though that exposes way more modules.


I don't think this is easy to change at all. Dune adds a wrapper module to the library name in case one doesn't exist with the same name. This library can also have its own code other than module aliases.
