### ISSUE TITLE
Documentation for testing existing projects on Melange

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [melange-re/melange#106]
To start off, maybe the single best thing to get out there quickly, is a quick tutorial for the non-initiate to make sure their (legacy BuckleScript, or ReScript, or OCaml) project *works with Melange too*. Bare-bones instructions to install it and compile existing BS/RS/RE/ML projects that are built on top of various tooling stacks would go a *long way* towards reassuring people that Melange won't go the way ReScript did, and build some initial goodwill and help onboard folks.

Melange (named pretty well) is kinda sitting at the intersection of a lot of tools, a lot of configuration, and just … A Lot for someone who's not constantly neck-deep in the OCaml ecosystem like you or I are. A 'batteries-included' quickstart tutorial that respects the visitor's time (i.e. minimal prose, maximal instructions) would be fantastic.

Personally, I'm a huge fan of the way [Babel handles this](https://babeljs.io/setup):

<img width="1024" alt="Screen Shot 2021-03-31 at 5 46 25 PM" src="https://user-images.githubusercontent.com/200/113220582-f3d9db00-9272-11eb-945c-b9b4efacab99.png">

**Comment by anmonteiro** [comment]
An example to take inspiration from (I converted Relude to work with Melange): https://github.com/reazen/relude/pull/293

Additionally, we should also document that most PPXes should be compatible, especially if they're built with ppxlib!

**Comment by anmonteiro** [comment]
This is not too relevant anymore, and we have melange.re now.
