### ISSUE TITLE
RFC: format integrate ocamlformat

### ISSUE THREAD

**Issue by EduardoRFS** [melange-re/melange#108]
If we're going to provide a CLI to format code maybe we should integrate ocamlformat?

I'm not sure we want to incentivize people to use the `-format` to actually format code instead of transforming from one syntax to the other.

**Comment by anmonteiro** [comment]
If I recall correctly, the ocamlformat API is still unstable. I'd prefer to wait until it stabilizes before considering including another dependency.

Note also, for the future reader: `bsc -format` should have been named `-convert`, as it's not really a formatter per se.

**Comment by EduardoRFS** [comment]
Let's close this for now than
