### ISSUE TITLE
Preserve comments when using -format from ReScript

### ISSUE THREAD

**Issue by EduardoRFS** [melange-re/melange#109]
Because ReScript and Reason / OCaml uses a different comment format currently comments are lost when formatting from one to the other.

Ideally we would have the pipeline for both sides

- [ ] ReScript comments to OCaml comments
- [ ] OCaml comments to ReScript comments

## Related code

https://github.com/melange-re/melange/pull/86/files#diff-f961d58ec96d0c153c4246858004edb0919f7caa3b3ea2121e6527d039b74a40R149

**Comment by anmonteiro** [comment]
Not going to spend time on this.
