### ISSUE TITLE
Remove themes

### ISSUE THREAD

**Issue by anmonteiro** [melange-re/melange#111]
`bsb -init` and `-theme` are bloated and very hard to maintain. 

I'd prefer if we could maintain a set of blessed project templates in the melange-re org that folks can just clone with git. Or otherwise use [spin](https://github.com/tmattio/spin).

- 👍 It should be easier to find them
- 👍 it should be easier to contribute / keep them up to date with new releases of melange
- 👍 we don't bundle a virtual filesystem inside the melange binary

**Comment by Mathspy** [comment]
For integration with npm we can also use init packages (`npm init @melange/project`) 
Not saying this desirable or a good idea but it’s relatively simple and common in JS ecosystem [(see create-react-app)](https://github.com/facebook/create-react-app#npm)

Either ways strongly in favor of removing themes
