### ISSUE TITLE
Convert internal libraries to wrapped libraries

### ISSUE THREAD

**Issue by anmonteiro** [melange-re/melange#113]
The current dune library structure is an almost 1-to-1 port of a Makefile based build. When converting it, I had to use `(wrapped false)` everywhere to avoid changing many files.

We should do better here. Wrapped libraries are pretty advantageous to avoid leaking modules in the global namespace.

This needs some exploration in order to find the right structure for libraries, and I expect it to be a pretty invasive change.

**Comment by jchavarri** [comment]
> to avoid changing many files.

Maybe this is what you had in mind already, but to decrease the chances of conflicts with upstream we could alias all modules at the top of each file, e.g.

```ocaml
module Bsb_log = Bsb.Bsb_log
module Bsb_global_paths = Bsb.Bsb_global_paths
```

So code blocks remain untouched.

(We could `open` as well at the top, but then what's the point of wrapped libs? :)

**Comment by EduardoRFS** [comment]
@jchavarri even if we just open at the top, advantages of having it as a wrapped library is that people can use melange on userspace as a library without leaking the entire namespace.

Maybe write tests, maybe use it as a typechecker indirectly, maybe load cmj assets to analysis and etc.... Like people do with `compiler-libs`, having it not wrapped here will lead

**Comment by anmonteiro** [comment]
Libraries are sufficiently refactored now.
