### ISSUE TITLE
Warn the user when they aren't using melange.ppx and using mel.stuff

### ISSUE THREAD

**Issue by davesnx** [melange-re/melange#1131]
Took it from discord: https://discord.com/channels/235176658175262720/825155604641218580/1246411227861618788

```
(library
  (name jslib)
  (modes melange)
  (melange.runtime_deps "somefun.js"))
```

```
(* jslib *)
external do_calc : int -> int -> int = "doCalc"
[@@mel.module "./somefun"]

let x = 10

let our_calc (y: int) : int = do_calc x y
```

Could warn about not using `melange.ppx` and using `mel.module`.

**Comment by anmonteiro** [comment]
don't we have this from https://github.com/melange-re/melange/pull/911 ?
