### ISSUE TITLE
Emit TypeScript type definitions

### ISSUE THREAD

**Issue by jubnzv** [melange-re/melange#1180]
It would be beneficial to have the ability to automatically generate TypeScript type definitions from Melange, as is possible in [ReScript](https://rescript-lang.org/docs/manual/latest/typescript-integration).

This would enable users to gradually integrate Melange into a TypeScript project, eventually allowing a complete rewrite.

Otherwise, as far as I understand, the user must manually write TS type definitions for the generated JS and maintain them when making changes to the Melange project.

**Comment by davesnx** [comment]
Related https://github.com/melange-re/melange/issues/916

**Comment by anmonteiro** [comment]
This is a duplicate of #916
