### ISSUE TITLE
Align with upstream Clflags

### ISSUE THREAD

**Issue by anmonteiro** [melange-re/melange#119]
we're missing a few, e.g. -strict-sequence

**Comment by EduardoRFS** [comment]
- [ ] -strict-sequence
- [ ] -strict-formats
- [ ] -g
- [ ] -opaque

Probably -opaque and -g will be a noop for now

**Comment by anmonteiro** [comment]
I just marked this as a "good first issue". If someone is interested in giving this one a shot, you'd need to:

- read [`driver/main_args.ml`](https://github.com/ocaml/ocaml/blob/4.12.0/driver/main_args.ml) for the 4.12 distribution of the OCaml compiler
- diff ours + upstream command line flags
- come up with a proposed list of flags (as a comment in this issue) that we need to diff
- implement them, mostly in [`jscom/main/js_main.ml`](https://github.com/melange-re/melange/blob/fork/jscomp/main/js_main.ml)

**Comment by jozanza** [comment]
Okay here's the diff. I went through by hand, so forgive me if I missed something. Someone may want to double-check everything 😅 

---

**Key**

| Icon        | Flag Status           |
| ------------- |:-------------:|
| ❌ | not supported
| ✅ | supported
| ➕ | new (melange-only)

---

**Flags**

- ❌ `- <file>`
- ❌ `-a`
- ✅ `-absname`
- ❌ `-alert <list>`
- ❌ `-alias-deps`
- ❌ `-annot` (deprecated)
- ❌ `-app-funct`
- ❌ `-args <file>`
- ❌ `-args0 <file>`
- ✅ `-bin-annot`
- ❌ `-bs-d`
- ✅ `-c`
- ❌ `-cc <command>`
- ❌ `-cclib <opt>`
- ❌ `-ccopt <opt>`
- ✅ `-color`
- ❌ `-compat-32`
- ❌ `-config`
- ❌ `-config-var`
- ❌ `-custom`
- ❌ `-dcamlprimc`
- ❌ `-depend <options>`
- ❌ `-dinstr`
- ❌ `-dlambda`
- ❌ `-dllib <lib>`
- ❌ `-dllpath <dir>`
- ❌ `-dlocations`
- ❌ `-dno-locations`
- ❌ `-dno-unique-ids`
- ✅ `-dparsetree`
- ❌ `-dprofile`
- ✅ `-drawlambda`
- ✅ `-dsource`
- ❌ `-dtimings`
- ✅ `-dtypedtree`
- ❌ `-dtypes` (deprecated)
- ❌ `-dump-into-file`
- ❌ `-dunique-ids`
- ❌ `-error-style {contextual|short}`
- ❌ `-for-pack <ident>`
- ❌ `-g`
- ✅ `--help`
- ✅ `-help`
- ✅ `-i`
- ✅ `-I <dir>`
- ✅ `-impl <file>`
- ✅ `-intf <file>`
- ❌ `-intf-suffix <string>`
- ❌ `-intf_suffix <string>` (deprecated)
- ❌ `-keep-docs`
- ✅ `-keep-locs`
- ❌ `-labels`
- ❌ `-linkall`
- ✅ `-make-runtime`
- ❌ `-make_runtime` (deprecated)
- ❌ `-match-context-rows <n>`
- ❌ `-modern` (deprecated)
- ✅ `-no-alias-deps`
- ❌ `-no-app-funct`
- ❌ `-no-check-prims`
- ❌ `-no-keep-docs`
- ✅ `-no-keep-locs`
- ❌ `-no-principal`
- ❌ `-no-rectypes`
- ❌ `-no-strict-formats`
- ❌ `-no-strict-sequence`
- ✅ `-noassert`
- ❌ `-noautolink`
- ✅ `-nolabels`
- ✅ `-nopervasives`
- ✅ `-nostdlib`
- ✅ `-o <file>`
- ❌ `-opaque`
- ✅ `-open <module>`
- ❌ `-output-complete-exe`
- ❌ `-output-complete-obj`
- ❌ `-output-obj`
- ❌ `-pack`
- ❌ `-plugin <plugin>` (no longer supported)
- ✅ `-pp <command>`
- ✅ `-ppx <command>`
- ✅ `-principal`
- ❌ `-rectypes`
- ❌ `-runtime-variant <str>`
- ❌ `-safe-string`
- ✅ `-short-paths`
- ❌ `-stop-after`
- ❌ `-strict-formats`
- ❌ `-strict-sequence`
- ❌ `-thread` (deprecated)
- ✅ `-unboxed-types`
- ✅ `-unsafe`
- ❌ `-unsafe-string` (option not available)
- ❌ `-use-prims <file>`
- ❌ `-use-runtime <file>`
- ❌ `-use_runtime <file>` (deprecated)
- ✅ `-v`
- ✅ `-verbose`
- ✅ `-version`
- ❌ `-vmthread` (no longer supported)
- ❌ `-vnum`
- ✅ `-warn-error <list>`
- ✅ `-warn-help`
- ✅ `-w <list>`
- ✅ `-where`
- ❌ `-with-runtime`
- ❌ `-without-runtime`
- ➕ `-as-ppx`
- ➕ `-bs-ast`
- ➕ `-bs-cmi`
- ➕ `-bs-cmi-only`
- ➕ `-bs-cmj`
- ➕ `-bs-cross-module-opt`
- ➕ `-bs-diagnose`
- ➕ `-bs-D`
- ➕ `-bs-eval`
- ➕ `-bs-g`
- ➕ `-bs-gentype`
- ➕ `-bs-internal-check`
- ➕ `-bs-jsx`
- ➕ `-bs-package-output`
- ➕ `-bs-list-conditionals`
- ➕ `-bs-loc`
- ➕ `-bs-noassertfalse`
- ➕ `-bs-no-bin-annot`
- ➕ `-bs-no-builtin-ppx`
- ➕ `-bs-no-check-div-by-zero`
- ➕ `-bs-no-version-header`
- ➕ `-bs-ns`
- ➕ `-bs-package-name`
- ➕ `-bs-re-out`
- ➕ `-bs-read-cmi`
- ➕ `-bs-refmt`
- ➕ `-bs-super-errors`
- ➕ `-bs-syntax-only`
- ➕ `-bs-unsafe-empty-array`
- ➕ `-bs-v`
- ➕ `-e`
- ➕ `-format`
- ➕ `-h`
- ➕ `-make-runtime-test`
- ➕ `-runtime`

**Comment by anmonteiro** [comment]
added `-rectypes` in #644, seems enough for now.
