### ISSUE TITLE
Installation problem: No solution found — Conflicting constraints: melange

### ISSUE THREAD

**Issue by jplew** [melange-re/melange#123]
I am attempting to follow the README instructions. 

1. `mkdir melange && cd melange`
2. `touch esy.json` and paste in:
```
{
  "dependencies": {
    "ocaml": "4.12.x",
    "melange": "melange-re/melange",
    "@opam/ocaml-lsp-server": "*"
  },
  "esy": {
    "buildsInSource": "unsafe",
    "build": [
      "ln -sfn #{melange.install} node_modules/bs-platform"
    ]
  },
  "installConfig": {
    "pnp": false
  }
}
```

3. `npm install`
4. `esy`

Gives the following error:
```
info esy 0.6.8 (using esy.json)
info checking https://github.com/ocaml/opam-repository for updates...
info checking https://github.com/esy-ocaml/esy-opam-override for updates...
info resolving esy packages: done
info solving esy constraints: done
error: No solution found:

Conflicting constraints:
  melange ->
  melange -> melange@github:melange-re/melange


esy: exiting due to errors above
```

Running the same command with verbose logging (`esy -v -v -v`) yields:

Mac error log:
https://gist.github.com/jplew/f7839b9cb1e5a515308c2c18aa890ad8

WSL (Ubuntu) log:
https://gist.github.com/jplew/155a63be1f56a5f937cc8c18a1909e0e

I tried `rm -rf _esy && rm -rf ~/.esy` and got the same error.

Using this in the package.json also fails:
```
    "melange": "melange-re/melange:esy.json",
```

or

```
  "dependencies": {
    "ocaml": "4.12.x",
    "melange": "*"
  },
  "resolutions": {
    "melange": "melange-re/melange#19d7c4be15c473b0b139772bd229e2ca3b3e2da4"
  },
```

**Comment by EduardoRFS** [comment]
@jplew can you share what is in your `package.json`?

**Comment by EduardoRFS** [comment]
Ok, we probably found the problem, your folder is called `melange` and your `esy.json` doesn't have a name field, this means that the name of your package is `melange` and it is essentially `melange` depending on `melange`.

```json
{
  "name": "not-melange",
  "dependencies": {
    "ocaml": "4.12.x",
    "melange": "melange-re/melange",
    "@opam/ocaml-lsp-server": "*"
  },
  "esy": {
    "buildsInSource": "unsafe",
    "build": [
      "ln -sfn #{melange.install} node_modules/bs-platform"
    ]
  },
  "installConfig": {
    "pnp": false
  }
}
```

Should fix

**Comment by EduardoRFS** [comment]
kudos to @joseeMDS for noticing that, will update the readme

**Comment by jplew** [comment]
that fixed it! Thanks for your help.
