### ISSUE TITLE
Support "dual" js outputs

### ISSUE THREAD

**Issue by jchavarri** [melange-re/melange#127]
Some projects use both `es6` and `commonjs`:

```
"package-specs": [
  {
    "module": "es6",
    "in-source": true
  },
  "commonjs"
],
```

One use case is that Jest support for es6 is not there yet and one can use Babel plugin, but it has many caveats. So dual output allows for Jest to consume `commonjs` without struggling much, and then use `es6` for lighter application bundles.

With latest Melange, the config above leads to `bs.js` files to appear both in-source and in `_build` in the `commonjs` format. I tried changing their ordering etc but it doesn't seem to have any impact.

**Comment by anmonteiro** [comment]
I took a brief look at this.

This is a little harder than I initially thought, because both output modes share the same extension.

it'd be made easier if we switched to `.mjs` for es6 outputs, but that has other problems.

**Comment by EduardoRFS** [comment]
@anmonteiro maybe we can move the assets like dune to hidden folders under `_build`, `.melange.eobjs/es6` and `.melange.eobjs/cjs`.

Then add a symlink to the preferred one?

**Comment by anmonteiro** [comment]
After some more investigation, we can support this easily if different `package-specs` declare different suffixes.

my proposed approach is:

- when parsing a bsconfig.json that has multiple package specs, warn if they don't have different suffixes.
- if a package has multiple specs with the **same suffix**, pick the first one
- if a package has multiple specs with **different suffixes**, generate both (declare e.g. `.bs.js` and `.mjs` in the dune generated rules)
