### ISSUE TITLE
Format repo using ocamlformat

### ISSUE THREAD

**Issue by bikallem** [melange-re/melange#155]
Should we use ocamlformat to format the repo? Perhaps use the dune repo style  https://github.com/ocaml/dune/blob/main/.ocamlformat ?

**Comment by EduardoRFS** [comment]
+1 on this

**Comment by anmonteiro** [comment]
The reason why we haven't done this, and are unlikely to do soon, is that it'd make cherry picking upstream patches way harder.

**Comment by bikallem** [comment]
Thanks. Makes sense regarding upstream cherry picking.
