### ISSUE TITLE
dune watch mode

### ISSUE THREAD

**Issue by EduardoRFS** [melange-re/melange#16]
I'm opening this issue to track the status of dune watch mode. TLDR: I would like to be able to just run `dune build @bsb_world -w`. Like described at #15 

At https://github.com/anmonteiro/bucklescript/pull/14#discussion_r594052294 @anmonteiro mentioned that this will be a problem because of the regenerated dune files, not sure if that's the case as normally dune can detect changes in the dune file while running.

**Comment by anmonteiro** [comment]
Using dune's builtin watcher would be interesting, if we can make it work. 

Right now there's sort of a circular dependency, as `bsb` generates dune rules, and `dune --watch` would have to call `bsb` after a file changes.


Open to more ideas if others have some.
