### ISSUE TITLE
"Multiple rules" Dune error if library contains artifacts with same suffix as Melange app

### ISSUE THREAD

**Issue by jchavarri** [melange-re/melange#172]
Melange commit: 1921408c0a6d6fe80396a3ef3724676cf7b8792d.

I ran into this when building a project with `reason-react`. It seems that if a library contains artifacts with the same suffix that is being used by `bsconfig.json`, Dune will complain due to multiple rules for the `*js` files.

If using this config in `bsconfig.json`:

```
  "package-specs": [
    {
      "module": "es6",
      "suffix": ".js"
    }
  ],
```

```
$ esy x bsb -make-world
info esy 0.6.8 (using esy.json)
info fetching: done
info installing: done
Error: Multiple rules generated for
_build/default/node_modules/reason-react/src/React.js:
- file present in source tree
- dune.bsb:10
Hint: rm -f node_modules/reason-react/src/React.js
error: command failed: 'bsb' '-make-world' (exited with 1)
esy-build-package: exiting with errors above...
error: build failed with exit code: 1
```

Full repro: 
[error_suffix_duplicated_rules.zip](https://github.com/melange-re/melange/files/6295656/error_suffix_duplicated_rules.zip)

Note the issue can be fixed by either:

- Removing `.js` files from node_modules as recommended
- Upgrading to `@rescript/react` which doesn't include artifacts anymore
- Using a different suffix

But I thought it was worth tracking just in case other libraries includes any artifacts as well.

**Comment by EduardoRFS** [comment]
If we want an workaround it would be possible to detect if the `.js` is present in source and mark it to be promoted, but not sure if that's a great idea.

But that could also be done by making melange remove the `.js`.

**Comment by jchavarri** [comment]
> But that could also be done by making melange remove the `.js`.

Yes, this could be an option. But note it affects any allowed extension (`bs.js`, `.cjs` etc). I don't know if it's a bit too much that Melange removes files from sources... maybe this is a wontfix and we have to solve it in a case by case basis (worst case scenario, forking the offending library to not include build artifacts).

**Comment by anmonteiro** [comment]
I think we can explore telling dune about it by using `(mode fallback)`. I'll take a look soon.

**Comment by anmonteiro** [comment]
I explored this a little bit, and `(mode fallback)` only works if all targets are present in the source tree. The package you mentioned only promoted the `.js` files.

I'm tempted to close this one as "won't fix" because it's not straightforward to detect or implement JavaScript artifact detection.

**Comment by idkjs** [comment]
Hey folks. So what is the recommend workaround at this point if you want to keep using `.re` files? Thanks.

**Comment by anmonteiro** [comment]
This can be fixed by adding `"in-source": true` to the package spec that has the conflicting suffix. Closing as a documented workaround.
