### ISSUE TITLE
Regression: apps can't use modules with same names as stdlib ones

### ISSUE THREAD

**Issue by jchavarri** [melange-re/melange#173]
Somewhere between 0fe76c5645e966ccab8b954675c1cd89608af38a (was working) and 7897dc82a5028203ccc47a4a4443bf5a924021ca (breaks), something changed that makes now impossible to have a module in a Melange app with the same name as stdlib one.

I noticed as we have React components named `Stack` that fail to build now. I think it's caused by `-I .../lib/melange`?

Easy repro:

- In a file `stack.ml`:

```ocaml
let t = 1
```

- In another `foo.ml`:

```ocaml
Js.log Stack.t
```

Error:

```
$ esy x bsb -make-world
1 | Js.log Stack.t
           ^^^^^^^
Error: Unbound value Stack.t
```

Same happens with other stdlib modules (`Random`, `Filename`...)

**Comment by anmonteiro** [comment]
I talked briefly to @EduardoRFS about this, and we think this is related to the order in which we include the Melange runtime / stdlib artifact path.

Right now we're prepending it in https://github.com/melange-re/melange/blob/1921408c0a6d6fe80396a3ef3724676cf7b8792d/jscomp/core/bs_conditional_initial.ml#L83

we should probably try inserting it at the end and seeing if that fixes it.

**Comment by jchavarri** [comment]
I tried the above suggestion:

```ocaml
Clflags.include_dirs := List.append !Clflags.include_dirs [(Lazy.force Js_config.stdlib_path)];
```

but still got the same error. I am trying to see differences in commands with `dune --verbose`
