### ISSUE TITLE
`esy bsb` not workling

### ISSUE THREAD

**Issue by EduardoAraujoB** [melange-re/melange#180]
So I was following the setup described in the  `README`, but I had this issue
![image](https://user-images.githubusercontent.com/42449213/115125834-2be65b00-9fa1-11eb-9726-8b98e007b763.png)
as you can see, I already installed the dependencies and my esy version is `0.6.10` and yarn is on `1.22.5` as well

**Comment by anmonteiro** [comment]
Did you follow the installation in the readme? Are you sure melange got linked under `node_modules`?

**Comment by EduardoRFS** [comment]
This `README` is about building melange to development of melange itself, maybe we should clarify this?

Anyhow, you can try https://github.com/melange-re/melange-basic-template/

**Comment by EduardoAraujoB** [comment]
oh, I got it, I was trying to use `esy bsb` inside melange, didn't knew that I need to use it as a dep in another project

**Comment by EduardoAraujoB** [comment]
maybe a doc update can clarify this
