### ISSUE TITLE
Todo in `jscomp/bsb/bsb_parse_sources.ml`

### ISSUE THREAD

**Issue by EduardoAraujoB** [melange-re/melange#187]
So, I was reading the `jscomp/bsb/bsb_parse_sources.ml` and I found a `todo` in the code, it's kinda ok to have todos in the code if you're on a small project that peoples will read your comment soon, but this project have a lot of files and is pretty easy to forget and didn't go back to check the todo, that's why I'm opening this issue, to make this more documented

![image](https://user-images.githubusercontent.com/42449213/115599044-7aea0400-a2b1-11eb-992d-baab2d861fe2.png)

**Comment by EduardoRFS** [comment]
It's okay to have TODOs in big projects, the Linux kernel itself has a lot of them. But agreed, having an issue for every case is helpful. I would just ask that instead of an image you added the line link.

**Comment by EduardoAraujoB** [comment]
the line link is on the image, but it's the line `450` to `452` of the `jscomp/bsb/bsb_parse_sources.ml`

**Comment by EduardoRFS** [comment]
https://github.com/melange-re/melange/blob/fork/jscomp/bsb/bsb_parse_sources.ml#L450

This is the kind of link I'm talking about, notice that it includes #L450 at the end
