### ISSUE TITLE
Expose react-ppx as ppxlib

### ISSUE THREAD

**Issue by jchavarri** [melange-re/melange#191]
I was testing [ppx_jsx_embed](https://github.com/melange-re/ppx_jsx_embed) and realized that it performs the 1st step of the conversion (the reason ppx) but not the 2nd (rescript-react ppx), which leads to errors of the kind: `Error: Unbound value div`.

I wonder if it'd make sense that melange exposes a `rescript-react-ppx` library so that one can configure bsconfig to apply it, together with `ppx_jsx_embed`, in sequence?

**Comment by jchavarri** [comment]
As @anmonteiro pointed out, the react ppx gets applied when adding this to bsconfig:

```
"reason": { "react-jsx": 3 },
```

`ml`  files get processed by this ppx since https://github.com/melange-re/melange/pull/140.

**Comment by EduardoRFS** [comment]
I think keeping this open is desirable as moving react-ppx to ppxlib would also be probably a performance win

**Comment by jfrolich** [comment]
Why would this be a performance win? I thought the ReScript people say that `ppxlib` degrades performance?

**Comment by jfrolich** [comment]
Ah I think because this reduces all ppx's to a single pass?

**Comment by anmonteiro** [comment]
this was done in https://github.com/melange-re/melange/pull/517
