### ISSUE TITLE
[dune] Relax bsc so that it allows to build files without .ml extension

### ISSUE THREAD

**Issue by jchavarri** [melange-re/melange#194]
Dune generates some internal files that have `.ml-gen` extension for wrapped libraries.

Right now, when calling `bsc` it will complain with an error like `don't know what to do with foo.ml-gen`. 

For now, I am patching dune to have these files ending with `.ml`: https://github.com/ocaml/dune/commit/5bd6373528e4d0da960ad14708b0185f7b079b19 

But ideally bsc would emulate ocamlc and allow to build files with custom extensions.

This is the place where related error is currently printed 

https://github.com/melange-re/melange/blob/415ff6390044b12c920be8bb049053ea6b2c257a/jscomp/main/js_main.ml#L154

**Comment by EduardoRFS** [comment]
What I'm doing on my setup is to enable `-impl` + `stdout` so that I can do `bsc anything.ml > js`

**Comment by EduardoRFS** [comment]
#196 should allow this

**Comment by idkjs** [comment]
Lets say you have `Lib.re` with 
```reason
let log = (s)=> Js.log(s)
```

and `Uselib.re` with 
```reason
Js.log("Hello, Reason!")
Lib.log("Hello, lib")
```

How would you combine them?

Running  `bsc Lib.re, Uselib.re > lib.js` get you an error.

```sh
bsc Lib.re, Uselib.re > lib.js
can not handle multiple files
```

Thanks.
