### ISSUE TITLE
[Feature Request] Exposing Syntax Formatter in a Library

### ISSUE THREAD

**Issue by Lomand** [melange-re/melange#228]
This would be quite handy in tools that rely on conversion between `.ml`, `.re`  and `.res` files and their interfaces.

Similar functionality was accessible in Reason, having it with Rescript would be quite a feature.
https://github.com/reasonml/reason/blob/master/docs/USING_PARSER_PROGRAMMATICALLY.md

**Comment by anmonteiro** [comment]
We don't link in any parsers in the melange core anymore. This is best done by other tooling.
