### ISSUE TITLE
Using N-API to run ocaml with nodejs

### ISSUE THREAD

**Issue by enieber** [melange-re/melange#229]
In nodejs has possiblity to use native code with n-api like [node-rs](https://github.com/napi-rs/node-rs). If melange can compile to native code call using n-api is very nice.

**Comment by anmonteiro** [comment]
This is possible with OCaml proper (see [this talk](https://www.youtube.com/watch?v=EEIGi1lP-v0), for example).

Melange doesn't need to take part in that.
