### ISSUE TITLE
Add melange to OPAM

### ISSUE THREAD

**Issue by Drakonis** [melange-re/melange#265]
As stated on the issue's title, melange is still not available on OPAM.

**Comment by jchavarri** [comment]
@anmonteiro are you ok with publishing on opam at this time? I can do it, just would need to know if using a version like v0.1 is ok.

**Comment by anmonteiro** [comment]
I wanna wait until Dune 3.5 is released so that we can include #350, which will remove the need for a custom installation script, and streamline installation on all supported package managers.

**Comment by anmonteiro** [comment]
It'd be nice to set up at least 1 CI run that exercises the OPAM flow, too.

**Comment by anmonteiro** [comment]
Started by releasing `melange-compiler-libs` in  https://github.com/ocaml/opam-repository/pull/22283

**Comment by jchavarri** [comment]
> It'd be nice to set up at least 1 CI run that exercises the OPAM flow, too.

Started #369, waiting for dune 3.5 to be released to check that all works fine.

**Comment by anmonteiro** [comment]
https://github.com/ocaml/opam-repository/pull/22355
