### ISSUE TITLE
Unify `Bsb_pkg.resolve_bs_package` and `Bsb_path_resolver.resolve_import_map_package`

### ISSUE THREAD

**Issue by anmonteiro** [melange-re/melange#300]
They should be called from the same entrypoint rather than us having to remember to call both

**Comment by anmonteiro** [comment]
Maybe @nordfjord is interested in sending a PR?

**Comment by nordfjord** [comment]
Good hunch. [There's one place](https://github.com/melange-re/melange/blob/fork/jscomp/bsb/bsb_build_util.ml#L127) where `resolve_bs_package` is called but `resolve_import_map_package` is not.

I wonder if that's a problem 🤔.

I'll open the PR to at least unify the current situation

**Comment by anmonteiro** [comment]
fixed in #304
