### ISSUE TITLE
Adding -open flag in bsc-flags does not open modules

### ISSUE THREAD

**Issue by osener** [melange-re/melange#317]
We have a project that has `"bsc-flags": ["-open Belt"]` in the bsconfig.json. It builds when I add `open Belt` to every source file, but it would be nice to have this working with Melange.

I created a repo that demonstrates the issue: https://github.com/osener/melange-open-issue

```shell
$ esy mel build
File "melange-open-issue/_build/default/src/Main.re", line 1, characters 0-13:
1 | Array.forEach([|1, 2, 3|], Js.log);
    ^^^^^^^^^^^^^
Error: Unbound value Array.forEach
Hint: Did you mean for_all?
```

Rules in dune.mel contain `-open` flag but it does not seem to be used for some reason.

```scheme
(rule
(targets  Main.ast)
 (deps (:inputs  Main.re)  ../.melange.eobjs/.bsbuild)
(action
 (run melc  -w a -bs-jsx 3 -open Belt -absname -bs-ast -o %{targets} %{inputs}))
(enabled_if %{bin-available:melc}) )
```

**Comment by osener** [comment]
I re-created the lockfile and made sure Melange is using latest HEAD, but I'm still getting the same error. Could you check this repo again? https://github.com/osener/melange-open-issue.

Thanks in advance!

PS: I forgot to update that repo with my reproduction of the issue. Now it should all be up to date, including Melange HEAD.

**Comment by anmonteiro** [comment]
Thanks, I found the bug. #318 fixes it

**Comment by osener** [comment]
This works great, thank you!
