### ISSUE TITLE
Allow using a PPX without passing the dependency on

### ISSUE THREAD

**Issue by mlms13** [melange-re/melange#325]
**The problem:**

Bastet, Relude, and presumably other libraries make use of `bisect_ppx` during development/CI to collect test coverage stats. In an ideal world, users of those libraries wouldn't also have to depend on `bisect_ppx`, because it's a dev-only tool that at various points has caused pain when building on Windows, with the Rescript compiler, etc. Currently, I don't believe it's possible to make it a `devDependency`, because the `ppx-flags`[field in our bsconfig](https://github.com/reazen/relude/blob/main/bsconfig.json#L37-L45) will try to run during every build, and it will fail in this case if it doesn't find `bisect_ppx`.

**Maybe a potential solution:**

@aantron [had proposed](https://github.com/rescript-lang/rescript-compiler/issues/3761) adding a "dev" version of the `ppx-flags` field to `bsconfig.json`. This could theoretically allow users of Relude to build a non-development version of the library that skips the `bisect_ppx` step. There was even [a Bucklescript PR](https://github.com/rescript-lang/rescript-compiler/pull/3715) that attempted to fix this, but it was never merged.

**Related info:**

- [Dune support for bisect_ppx](https://github.com/ocaml/dune/issues/57)

**Comment by anmonteiro** [comment]
This is related to #192 and https://github.com/melange-re/melange/issues/92

**Comment by anmonteiro** [comment]
Same reasoning as https://github.com/melange-re/melange/issues/92, we'll get dune profiles for free with the deeper dune integration.
