### ISSUE TITLE
Out of source builds

### ISSUE THREAD

**Issue by anmonteiro** [melange-re/melange#33]
- We're almost there, but I think we're still generating namespacing stuff in-source
- we should also not require bs-platform to be linked under node_modules

**Comment by EduardoRFS** [comment]
> we should also not require bs-platform to be linked under node_modules

It seems like this is not needed anymore, as I tried locally with esy and "it just works™"

**Comment by anmonteiro** [comment]
Some more details here on what's missing. I'll be adding more to the list as I remember / play with it.

- [ ] don't create lib/ocaml
- [ ] don't create lib/bs. there are 2 parts to this that need to be put somewhere else
    - [ ] stop generating `.sourcedirs.json` in `lib/bs/` when `-install` is passed
    - [ ] stop generating `.bsbuild` in `lib/bs/`
- [ ] introduce the `$BSLIB` env variable (probably needs an RFC) to find dependencies outside of `node_modules`
  - [ ] generate `import` / `require` code that points to paths outside of `node_modules`

**Comment by anmonteiro** [comment]
https://github.com/melange-re/melange/pull/296 and https://github.com/melange-re/melange/pull/306 allow out of source builds.
