### ISSUE TITLE
Order of preprocessor isn't working as expected

### ISSUE THREAD

**Issue by davesnx** [melange-re/melange#341]
Hey @anmonteiro,

I'm trying to replace React_jsx_ppx3 to an external one (in this case just migrated to ppxlib).

There's seems to be an unexpected behaviour when I have the basic setup: https://github.com/davesnx/melange-external-ppx-bug

```
→ ~/C/g/m/melange-external-ppx-bug on main ✗ esy build
info esy build 0.6.12 (using esy.json)
File "ReactApp", line 1:
Error: Unbound type constructor Js.t
``` 

It seems like Js.t isn't available on the compilation, I checked extensively that the transformation works in isolation (https://github.com/ml-in-barcelona/react-jsx-ppx), to be extra sure that the transformation works: Running the ppx manually with the code, gets the output correct.

My first assumption is that there's a difference when running external ppx (ppx-flags) and React_jsx_ppx3, regarding the order? Tried to understand when looking at ppx_entry.ml but can't clear my head on this.

**Comment by anmonteiro** [comment]
fixed in https://github.com/ml-in-barcelona/react-jsx-ppx/pull/2
