### ISSUE TITLE
Experiment not generating `.cmt{,i}` files

### ISSUE THREAD

**Issue by anmonteiro** [melange-re/melange#344]
When we have the dune integration, we can experiment with letting `ocamlc` generate these.

**Comment by anmonteiro** [comment]
This isn't actionable, we need these for editor integration.

**Comment by jchavarri** [comment]
> we need these for editor integration

I understood the idea was to have `ocamlc` generate them? Not not generating them at all.

**Comment by anmonteiro** [comment]
We can track this in #346, since that's a blocker for this.
