### ISSUE TITLE
Make `.cmj`s "package spec" agnostic

### ISSUE THREAD

**Issue by jchavarri** [melange-re/melange#358]
At the moment each cmj needs to know about all possible package specs present in the final js artifacts.

Maybe there is a way to for the cmj to contain this information without having to be explicit about the module system that will be used later on.

This would be useful to generate a single `.cmj` and the be able to easily produce `js` artifacts for es6 and commonjs.

Related PR:
- https://github.com/melange-re/melange/pull/199.

**Comment by anmonteiro** [comment]
This should work with `-bs-stop-after-cmj`. A few examples:

```shell
$ melc foo.re -bs-stop-after-cmj

$ ls
foo.cmi  foo.cmj  foo.cmt  foo.re

$ melc -bs-package-name this -bs-package-output commonjs:/doesnt/exist:.bs.js ./foo.cmj -o lol.js

$ ls
foo.cmi  foo.cmj  foo.cmt  foo.re  lol.bs.js # only the suffix and module system is taken from bs-package-output

```
