### ISSUE TITLE
port bigint

### ISSUE THREAD

**Issue by anmonteiro** [melange-re/melange#435]
https://github.com/rescript-lang/rescript-compiler/pull/5539/files

**Comment by anmonteiro** [comment]
done in #563

**Comment by texastoland** [comment]
I saw the `Js.Bingint.t` type but is it a placeholder? I skimmed the compiler changes but it wasn't clear what they did. AFAICT there's no built-in way to declare literals or do math.

**Comment by anmonteiro** [comment]
It's just a placeholder, currently. Just like `melange.dom`.

The goal is to eventually start adding functions from the JS Bigint API. If you're interested in using the API, I'd be happy to start accepting PRs adding functions to `Js_bigint.ml`.

Once we have that, we could consider adding some sugar in the Melange PPX for bigint arithmetic, e.g. `1M + 2M = 3M`. ppxlib [allows this]( understands `1M + 2M == 3M` as Js.Bigint.t,, using constant rewriting from ppxlib https://ocaml-ppx.github.io/ppxlib/ppxlib/writing-ppxs.html#constant-rewriting).
