### ISSUE TITLE
melc: internal error, uncaught exception

### ISSUE THREAD

**Issue by dboris** [melange-re/melange#439]
Trying to compile a [rescript-tea](https://github.com/darklang/rescript-tea) project with melange, I get the following error:
```
opam exec -- mel build
File "dune.mel", line 3954, characters 1-272:
3954 |  (rule
3955 | (targets  web_xmlhttprequest.ast)
3956 |  (deps (:inputs  web_xmlhttprequest.res.pp.ml)  ../../../.melange.eobjs/node_modules/reason-tea/.bsbuild)
3957 | (action
3958 |  (run melc  -w a -bs-cross-module-opt -absname -bs-ast -o %{targets} %{inputs}))
3959 | (enabled_if %{bin-available:melc}) )
melc: internal error, uncaught exception:
      File "jscomp/frontend/ast_exp_apply.ml", line 252, characters 17-23: Assertion failed
```
These are the installed versions of relevant libs:
```
mel                     0.3.1         Build system for Melange that defers to Dune for build orchestration
melange                 0.3.1         Toolchain to produce JS from Reason/OCaml
melange-compiler-libs   0.0.1-414     Compiler libraries for Melange, a toolchain to produce JavaScript from OCaml
meldep                  0.3.1         Melange counterpart to `ocamldep` that understands Melange-specific constructs
```

**Comment by anmonteiro** [comment]
Appreciate the report. Here's what's going on:

- we introduced a ppx to convert some rescript AST idioms to a format melange understands (in #278)
- turns out that conversion was wrong for `#=` cases (rescript equivalent: `foo["bar"] = assignment`)
- Fixed this in #441

**Comment by dboris** [comment]
Thank you for the quick fix.

An unrelated question: 
Is there a way to convert between the different syntaxes supported by melange, eg rescript to reason or ocaml?

**Comment by anmonteiro** [comment]
Yes see https://github.com/melange-re/melange/issues/417#issuecomment-1321009978
