### ISSUE TITLE
`melc` fails if flag is duplicated

### ISSUE THREAD

**Issue by jchavarri** [melange-re/melange#456]
Just for the sake of consolidation with upstream, reporting an issue I found.

```
$ touch foo.ml
$ ocamlc -strict-sequence -strict-sequence foo.ml
$ melc -strict-sequence -strict-sequence foo.ml
melc: option '--strict-sequence' cannot be repeated
Usage: melc [OPTION]… [filenames]…
Try 'melc --help' for more information.
```

My ideal fix would for upstream to fail like `melc` does if a flag is repeated, but I am not sure it is likely to happen. @anmonteiro wdyt?

**Comment by anmonteiro** [comment]
I'm not sure what to do about this. 

- Using `cmdliner` provides a really nice API, but it also means it adds the "cannot be repeated checks"
- `ocamlc` et al. use `Stdlib.Arg` which I believe doesn't have repetition checking


A compromise would be to convert most options to `opt_all` as stated in [this comment](https://github.com/dbuenzli/cmdliner/issues/113#issuecomment-549454708)

**Comment by anmonteiro** [comment]
I think we're unlikely to support this. It's easy to omit repeated arguments in dune with `(flags :standard \ --dont-repeat)`
