### ISSUE TITLE
React JSX PPX umbrella issue

### ISSUE THREAD

**Issue by anmonteiro** [melange-re/melange#459]
Extracted from [this comment](https://github.com/ocaml/dune/pull/6476#discussion_r1024322957)

We should make a note to remove the -bs-jsx-3 stuff eventually. Here's my rough plan:

- move the React JSX PPX out of the compiler (https://github.com/melange-re/melange/pull/396)
- distribute this new package with melange
- nudge users to change to (preprocess (pps reactjs_jsx_ppx)) rather than (flags :standard -bs-jsx 3)
- Delete this line in the merlin generated config

**Comment by jchavarri** [comment]
> nudge users to change to (preprocess (pps reactjs_jsx_ppx)) rather than (flags :standard -bs-jsx 3)

as @rgrinberg pointed out, this won't be possible until everything in the ppx (fast pipe, ## operator, etc) are migrated to another `melange-ppx`, so there is one missing step in the list.

**Comment by anmonteiro** [comment]
What's the part that's not possible? can't we use the melange ppx without `-bs-jsx 3`?

**Comment by jchavarri** [comment]
Sorry, I should have pointed to this item instead:

> Delete this line in the merlin generated config

We can't remove the hack in merlin generated config until melange ppx is available independently.

**Comment by anmonteiro** [comment]
Oh I meant delete the bs-jsx arg from the Merlin config, not the whole line

**Comment by jchavarri** [comment]
I created https://github.com/melange-re/melange/issues/463 to track it.

**Comment by davesnx** [comment]
Updated https://github.com/melange-re/melange/pull/396 without being a breakage for users.

**Comment by jchavarri** [comment]
I think this issue is now done:
- move the React JSX PPX out of the compiler was done in https://github.com/melange-re/melange/pull/517
- delete the line in the merlin generated config was done in https://github.com/ocaml/dune/pull/7354
- bs-jsx flag was removed in https://github.com/melange-re/melange/pull/525
