### ISSUE TITLE
Destructuring record from known type works on ReScript but not on Melange

### ISSUE THREAD

**Issue by jchavarri** [melange-re/melange#462]
The following code used to work on BuckleScript/[ReScript](https://rescript-lang.org/try?code=LYewJgrgNgpgBAFTgXjgbwFBzgFwJ4AO8OK6AZiCAFxwDOOATgJYB2A5gL4DcG3GGsEsACGAa3ioAFAD8cNBADocAShQA+dFjiDylDqRw9sFEDz5A):

```reason
module T = {
  type t = {foo: string};
};

let make = (~t: T.t) => {
  let {foo} = t;
  foo;
};
```

But it fails in Melange (and OCaml, for that matters) with:

```
File "main.re", line 6, characters 8-11:
6 |   let { foo } = t in
            ^^^
Error: Unbound record field foo
```

I am just curious to know what's the cause? Is it due to the parser?

**Comment by anmonteiro** [comment]
There’s some reasoning in https://github.com/melange-re/melange/pull/161. That was a breaking change that caused some OCaml programs to not compile. We decided to revert it.

**Comment by jchavarri** [comment]
Thanks for clarifying! Makes sense 💯
