### ISSUE TITLE
Create melange-ppx as standalone ppx rewriter

### ISSUE THREAD

**Issue by jchavarri** [melange-re/melange#463]
There are a number of syntax transformations that Melange does internally, for example:

- Pipe first operator `|.`
- Object method selector `##` (and another less known `#=`)
- Processing of `bs` attrs
- ...

The main entry point is [bs_builtin_ppx.ml](https://github.com/melange-re/melange/blob/2dec6b553c36027b6550ee323f264f7d4662d966/jscomp/frontend/bs_builtin_ppx.ml).

For merlin to work properly, we currently run `melc` as ppx from dune (see https://github.com/ocaml/dune/pull/6476). Ideally in the future there should be a `melange-ppx` that allows to do this processing like with any other ppx, so that merlin doesn't require any explicit hacks to work with Melange.

**Comment by anmonteiro** [comment]
this was done in #534
