### ISSUE TITLE
Installing and running via flake fails due to incorrect melange-compiler-libs version

### ISSUE THREAD

**Issue by bbenne10** [melange-re/melange#498]
Hi! I'm attempting to get a more thorough understanding of the state of the current "fullstack" web ecosystem surrounding OCaml. As part of this, I am attempting to update my Reason-Todo application to use Melange. I was heartened to see Nix support as part of Melange's infrastructure. However, attempting to run `nix run github:melange-re/melange#melc -- --help` (as suggested by the README) currently fails with this (truncated to the relevant output, I believe): 

```
(cd _build/.sandbox/146003ac35c03f327975e2bcdf2be7a4/default && /nix/store/hfqmkiwkrjqzyn5546vq7vk18khfg182-diffutils-3.8/bin/diff -u test/missing-namespace.t/run.t test/missing-namespace.t/run.t.corrected)
--- test/missing-namespace.t/run.t      2023-02-28 15:08:43.381552793 +0000
+++ test/missing-namespace.t/run.t.corrected    2023-02-28 15:08:43.381675239 +0000
@@ -16,10 +16,25 @@
   var Curry = require("melange/lib/js/curry.js");
   var Melange__FieldsRequestDescr = require("./fieldsRequestDescr.js");
   
-  var dr = Curry._1(Melange__FieldsRequestDescr.Fields.Field_dsl.Aggregations.any, 2);
+  var dr = Curry._1(Melange__FieldsRequestDescr.Field_dsl.Aggregations.any, 2);
   
   exports.dr = dr;
   /* dr Not a pure module */
 
   $ node _build/default/dist/main.js
+  $TESTCASE_ROOT/_build/default/dist/main.js:7
+  var dr = Curry._1(Melange__FieldsRequestDescr.Field_dsl.Aggregations.any, 2);
+                                                          ^
+  
+  TypeError: Cannot read properties of undefined (reading 'Aggregations')
+      at Object.<anonymous> ($TESTCASE_ROOT/_build/default/dist/main.js:7:57)
+      at Module._compile (node:internal/modules/cjs/loader:1254:14)
+      at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
+      at Module.load (node:internal/modules/cjs/loader:1117:32)
+      at Module._load (node:internal/modules/cjs/loader:958:12)
+      at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
+      at node:internal/main/run_main_module:23:47
+  
+  Node.js v18.14.1
+  [1]
 
Done: 99% (5781/5791, 10 left) (jobs: 7)^M                                        ^MDone: 99% (5783/5791, 8 left, 1 failed) (jobs: 4)^M                                                 ^MDone: 99% (5783/5791, 8 left, 1 failed) (jobs: 4)
.......................................................................................................................................................................................................................
Ran: 215 tests in: 1.47 seconds.
OK
Done: 99% (5790/5792, 2 left, 1 failed) (jobs: 1)
```

Thinking I might be able to look into this, I cloned the repo and followed along with CONTRIBUTING.md to get the `ocaml-tree` subtree set up properly and ran the tests successfully with `dune runtest`. `nix run` still fails during check phase. I *think* this indicates a lock in need of updating? I see 1da4f469f, which locks `melange-compiler-libs` during CI. I checked out the commit in question in `melange-compiler-libs`, and I'm not sure I can grok quite what the provenance of that commit is (it doesn't exist in a branch and I'm frankly surprised it hasn't been garbage collected yet...)

How should I be running this as a flake? Is this expected? How can I help make it better?

**Comment by anmonteiro** [comment]
This happens because I messed up the overlay application order in flake.nix. #493 will fix this.

**Comment by anmonteiro** [comment]
#493 is merged, could you try again?

**Comment by bbenne10** [comment]
I can confirm that #493 has resolved the issue. Thanks!
