### ISSUE TITLE
Bring back original `Js.String.match_` return type

### ISSUE THREAD

**Issue by jchavarri** [melange-re/melange#521]
In https://github.com/melange-re/melange/commit/ccceb69d85afdf7743259bb9faca6f975ebe541f, the return type of `Js.String.match_` was modified.

This is the only reason why we have to use cppo in Ahrefs codebase to maintain compatibility with both bs-platform v9 and melange `main`.

It would be nice to revert that commit before publishing the first version of Melange, so users of ReScript that might want to migrate have a starting point to do so (v9).

Related discussion in https://github.com/melange-re/melange/pull/319#issuecomment-1279723865.

**Comment by anmonteiro** [comment]
I think we're so far past the point of supporting some old workflows that this is not really warranted. If you feel strongly about it, I'm OK reverting that patch in the [`mel`](https://github.com/melange-re/melange/tree/mel) branch that we keep to make the last release that will support bsconfig.json workflows.

**Comment by jchavarri** [comment]
I don't think it's necessary.

For anyone following now or in the future, here is how I solved this with Ahrefs code, while maintaining compatibility with both ReScript and Melange while migration is ongoing.

The solution requires using [cppo](https://github.com/ocaml-community/cppo).

You define conditional code in some file e.g. `Melange_string.cppo.ml`:
```ml
#ifdef MELANGE
  let match_ s regex =
    (Js.String2.match_ s regex |. Belt.Option.map) (fun arr ->
      (arr |. Belt.Array.map) (fun s ->
        (s |. Belt.Option.flatMap) (fun s ->
          match s = "" with
          | true -> None
          | false -> Some s)))
#else
  let match_ s regex =
    (Js.String2.match_ s regex |. Belt.Option.map) (fun arr ->
      (arr |. Belt.Array.map) (fun s ->
        match s = "" with
        | true -> None
        | false -> Some s))
#endif
```

Then add a rule to dune:

```dune
(rule
 (targets Melange__string.ml)
 (deps Melange__string.cppo.ml)
 (action
  (run %{bin:cppo} -D MELANGE %{deps} -o %{targets})))
```
