### ISSUE TITLE
https://melange.re is down

### ISSUE THREAD

**Issue by yatesco** [melange-re/melange#557]
Just a note :-).

<img width="648" alt="image" src="https://user-images.githubusercontent.com/181469/236238885-7f978f19-9709-484e-8ca3-e0c6f0df6b46.png">

**Comment by davesnx** [comment]
It's not meant to be up, yet! https://github.com/melange-re/melange/issues/208

**Comment by yatesco** [comment]
it's linked on the front page which made me assume it was up, and I was excited to read more about it. You are a victim of your own success :-) ;-)
