### ISSUE TITLE
Not possible to generate docs with OCaml 5

### ISSUE THREAD

**Issue by jchavarri** [melange-re/melange#603]
Documenting here something discussed offline.

At the moment, it is not possible to build the docs on an OCaml 5 switch:

```
$ dune build @doc
File "jscomp/runtime/.runtime.objs/byte/_unknown_", line 1, characters 0-0:
ERROR: File "../melange/bs_stdlib_mini.cmti":
not an interface
File "jscomp/runtime/.runtime.objs/byte/_unknown_", line 1, characters 0-0:
ERROR: File "../melange/caml_array.cmti":
not an interface
...
```

I assume the same problem happens with other versions of the OCaml compiler, like 4.13?

These are the options I can think of:
- Constraint the version of the OCaml compiler to 4.14 in the opam file (prob not very scalable)
- Include multiple versions of the necessary files in `melange-compiler-libs` and use one or the other depending on the underlying toolchain version?

**Comment by jchavarri** [comment]
Ftr, this limitation might be the same one causing issues in ocaml.org docs ci:

https://docs.ci.ocaml.org/job/2023-06-03/075504-voodoo-do-ce6f01#L2526

```
odoc: internal error, uncaught exception:
      Cmi_format.Error(_)
      Raised at Cmi_format.read_cmi in file "file_formats/cmi_format.ml", line 82, characters 6-21
      Called from Odoc_odoc__Depends.for_compile_step_cmi_or_cmti in file "src/odoc/depends.ml", line 37, characters 18-62
      Called from Dune__exe__Main.Depends.Compile.list_dependencies in file "src/odoc/bin/main.ml", line 689, characters 17-72
      Called from Cmdliner_term.app.(fun) in file "cmdliner_term.ml", line 24, characters 19-24
      Called from Cmdliner_eval.run_parser in file "cmdliner_eval.ml", line 34, characters 37-44
```

**Comment by tmcgilchrist** [comment]
Just confirming this because it came up while debugging ocaml.org docs ci.
On 4.14.1 it works fine:
```
$ opam switch create . 4.14.1 --no-install
$ opam install odoc.2.2.1 melange.1.0.0 
$ ocaml --version
The OCaml toplevel, version 4.14.1
$ odoc compile-deps _opam/lib/melange/runtime/melange/bs_stdlib_mini.cmi  
Bs_stdlib_mini 98304ed784bc5adfce3b91ff30dece61
```

On 5.0 it fails with:
```
$ opam switch create . 5.0.0 --no-install
$ opam install odoc.2.2.1 melange.1.0.0
$ odoc compile-deps _opam/lib/melange/runtime/melange/bs_stdlib_mini.cmi   
odoc: internal error, uncaught exception:
      Cmi_format.Error(_)
      Raised at Cmi_format.read_cmi in file "file_formats/cmi_format.ml", line 82, characters 6-21
      Called from Odoc_odoc__Depends.for_compile_step_cmi_or_cmti in file "src/odoc/depends.ml", line 37, characters 18-62
      Called from Dune__exe__Main.Depends.Compile.list_dependencies in file "src/odoc/bin/main.ml", line 689, characters 17-72
      Called from Cmdliner_term.app.(fun) in file "cmdliner_term.ml", line 24, characters 19-24
      Called from Cmdliner_eval.run_parser in file "cmdliner_eval.ml", line 34, characters 37-44
```

While the documentation build for melange.2.0.0 is fine with OCaml 5.1. See https://docs.ci.ocaml.org/package/melange.2.0.0

Is it possible to patch melange.1.0.0 to be more specific with the OCaml version it requires?

**Comment by jchavarri** [comment]
@anmonteiro mentioned his preference to allow melange.1.0.0 to be installed with multiple versions of OCaml. I am not sure if that preference could change now that 2.0.0 is out.

**Comment by anmonteiro** [comment]
With the release of Melange v2, and the fact that it only works on OCaml 5.1, I think I'd be OK tightening up the constraints in the opam repository. 

I had a dream, but it didn't pan out. @jchavarri was right all allong 😛
