### ISSUE TITLE
Adding GitHub Discussions to Melange Repo

### ISSUE THREAD

**Issue by XantreGodlike** [melange-re/melange#625]
I propose to enable GitHub Discussions in melange repo. It'll be space to discuss new features, answer questions, and more. It's like Issues but more flexible and conversational.

Pros:
Easy to organize and find topics.
Boosts community engagement.
Serves as a knowledge base.
Makes project more transparent.

**Comment by anmonteiro** [comment]
Thanks for the suggestion, let's try it out: https://github.com/melange-re/melange/discussions/626
