### ISSUE TITLE
RFC: Add `check-npm-deps` tool

### ISSUE THREAD

**Issue by jchavarri** [melange-re/melange#629]
We have started defining dependencies for Melange libraries using `opam` files ([example](https://github.com/melange-community/melange-testing-library)). This makes sense at the native toolchain level, so that packages can define with which version of `melange`, ppxs or any other native or melange libraries they are compatible. Unfortunately though, moving these specs to opam creates a disconnect with the JavaScript packages that the bindings depend on.

In native OCaml, this is solved through the `depexts` field, for [example](https://github.com/BinaryAnalysisPlatform/bap/blob/511b64ce7fcf619eae373a6a11c50c668a0cf311/bap-llvm.opam#L45):

```
depexts: [
  ["clang" "libncurses5-dev" "libzstd-dev"] {os-distribution = "ubuntu"}
  ["clang"] {os-distribution = "debian"}
  ["clang" "libxml2-dev"] {os-distribution = "alpine"}
  ["clang"] {os-distribution = "fedora"}
]
```

It would be nice to use a similar mechanism for Melange packages. Apparently the following definition of `depexts` is accepted[^1] by opam (at least in the tested version 2.1.2):

```
depexts: [
  ["react"] {os-family = "npm" & version = "^16.0.2"}
  ["react-dom"] {os-family = "npm" & version = "^16.0.2"}
]
```

Melange could include a binary `check-npm-deps` (or a better name) that would not install the JavaScript packages, but rather given the existing set of opam packages installed in the current opam switch, check in the `node_modules` folder for the availability of the `depexts` fields defined in those packages.

Calling 

```bash
$ check-npm-deps
```

would:

- Iterate through the opam files found in `$OPAM_SWITCH_PREFIX/.opam-switch/packages` to get all depexts with `os-family` set to `npm`
- For each depext `<npm-pkg>` found in the step above, check `node_modules/<npm-pkg>/package.json` and verify that the `version` field in the `package.json` satisfies the constraints defined in the `version` filter defined in the depext.

For the latter, esy includes [some utilities](https://github.com/esy/esy/blob/4f3202d0efd62be22e7f862b2d5d8ede803ae8e2/esy-package-config/SemverVersion.re) to work with semver and validate package versions against npm-like constraints.

For the former, parsing utilities for `opam` files can be found in either opam or dune sources.

### Limitations

- This new command would require adding a separate step for installing Melange projects. This downside is mitigated by the fact that this step is purely optional, and also by Melange projects already using [Makefiles](https://github.com/melange-re/melange-opam-template/blob/6f59fc0189a9c250c8542638fdc3a606e9c01d7b/Makefile#L21-L27) to make installation with both JavaScript and OCaml package managers easier.
- The check is only informative, but it would not perform any installation or upgrade of existing npm packages. To actual fix any missing package would require manual work from the user. This is more inconvenient but it removes a lot of complexity from the new tool implementation, as it does not have to deal with the handling of multiple package managers like npm or yarn, and leaves up to the user how to resolve the issue with the package manager of their choice

### Alternatives

- Embed this check in either dune or opam: this would be more complex, at least politically, as this is a use case quite particular to Melange and not general to OCaml projects
- Use alternative package managers like nix or esy, but this means probably harder integration with editor plugins, worse documentation, more limited maintenance, etc.

### Questions

- Should this new tool be part of the `melange` package? Or rather create a new one to contain it?

[^1]: Accepted in the sense that this configuration does not crash opam, but it is a no-op at the moment.

**Comment by jchavarri** [comment]
This might be best implemented as an opam plugin.

**Comment by davesnx** [comment]
If we ever want to do the installation as an option, detecting which package manager you have already is doable. This is the logic for a package that uses the right package manager across all subcommands for ([npm](https://docs.npmjs.com/cli/v6/commands/npm) · [yarn](https://yarnpkg.com/) · [pnpm](https://pnpm.js.org/en/) · [bun](https://bun.sh/)) https://github.com/antfu/ni/blob/main/src/detect.ts

**Comment by jchavarri** [comment]
Would be nice to add a flag to ignore specific libraries (in case the version installed differs, or some other reason). e.g. `opam check-npm-deps --ignore jest`.

**Comment by ELLIOTTCABLE** [comment]
Brought these up in an internal meeting, and wanted to record them here as well:

- `$PATH` is a complicated topic here. When/where opam might be running the `depext` checks may not be where the `package.json` is
  - Particularly in the case of 1. global packages (which a check might say "exists", but may not exist in the _correct_ way), 2. lerna / monorepos, where some packages may be hoisted to the monorepo root, and etc

- Transitive, multi-platform dependencies:
  - `opam1 -> opam2 -> npm1`: the "application" (root) doesn't have a `package.json`; 1. so _where_ (`$PATH` again, lol) are those packages getting installed, and 2. whose responsibility is doing so? (especially in the case of multiple transitive-to-npm paths)
  - `opam1 -> npm2 -> opam3`

- One alternative: if it can be made to work, `conf-packagejson` — an opam package who simply checks that, yes, "my" `package.json` dependency tree is correctly satisfied (`npm ci --dry-run` or whatever), and fails if it is not.
  - unsure where conf packages get run; unsure whether they have access to the package's source (i.e. anything other than the `opam` file itself)?

----

Anyway, one last personal observation: the absolute _minimum_ of "managing the interaction" is, IMHO, the only way. Deep integration is just always going to be too leaky; with Melange sitting as a bridge between two ecosystems, it's unavoidable, and thus, the most-hands-off approach seems like the smartest one. Already felt enough of this pain with both BuckleScript's and esy's attempts to sweep the bridge under the rug with leaky abstractions. 😅

**Comment by jchavarri** [comment]
ftr i am working on this in https://github.com/jchavarri/opam-check-npm-deps.

**Comment by anmonteiro** [comment]
This has been released to opam: https://github.com/ocaml/opam-repository/pull/24251
