### ISSUE TITLE
better error messages when melange.ppx is missing

### ISSUE THREAD

**Issue by EduardoRFS** [melange-re/melange#633]
Currently if you forget to add a melange.ppx on external code, it will fail at call site and not on declaration, which leads to all sorts of error messages such as `Unimplemented primitive used`.

Hinting melange.ppx could help a lot here, but also rejecting invalid externals at declaration. 

Additionally melange could detect the `[@bs.something]` stuff and hint as a warning that it was detected.

**Comment by davesnx** [comment]
We hit those each week and discussed this a lot. Probably adding `melange.ppx` automatically should be preferred. WDYT?

**Comment by anmonteiro** [comment]
Let me think about this more thoroughly. In those cases we should also identify `[@u]`, `##`, etc.
