### ISSUE TITLE
nix instructions result in missing reason-react-ppx library

### ISSUE THREAD

**Issue by joprice** [melange-re/melange#647]
I tried following the instructions in the readme for nix (https://melange.re/v1.0.0/getting-started/#nix), but got the error below when trying to use the shell, where `reason-react-ppx` is not found.

```
error: undefined variable 'reason-react-ppx'

       at /nix/store/ibn471c4gjzf8b47lq5g8mfxg1ka3fmb-source/nix/default.nix:68:28:

           67|     ];
           68|     checkInputs = [ ounit2 reason-react-ppx reason ];
             |                            ^
           69|
(use '--show-trace' to show detailed location information)
```

**Comment by anmonteiro** [comment]
Use my overlays instead of upstream nixpkgs

**Comment by anmonteiro** [comment]
It'd be nice to package up Melange for `nixpkgs` upstream too.

**Comment by joprice** [comment]
This is now building with the latest version of nix-overlays
