### ISSUE TITLE
Calling Float.abs produces error `melc: internal error, uncaught exception: File "jscomp/core/lam_convert.ml", line 293, characters 17-23: Assertion failed`

### ISSUE THREAD

**Issue by CalHinshaw** [melange-re/melange#650]
`abs_float` works fine.

**Comment by anmonteiro** [comment]
If anyone wants to take a stab at this one, the fix should be very similar to https://github.com/melange-re/melange/pull/476.

We need `Float.abs` to be a working JS external like `abs_float` in the Stdlib.
