### ISSUE TITLE
Compile a polymorphic variant to a desired string cleanly

### ISSUE THREAD

**Issue by jbhoot** [melange-re/melange#655]
In order to compile a polymorphic variant to a desired string value in JavaScript, the following approach is required:

```
type x =
  [ `Document_fonts [@bs.as "document-fonts"]
  | `Browser_fonts [@bs.as "browser-fonts"]
  ]
[@@bs.deriving jsConverter]

let a : x = `Document_fonts
let b = xToJs `Document_fonts
```

The assignments are compiled to 

```
var a = "Document_fonts";
var b = xToJs("Document_fonts");
```

out of which, `b` is correctly assigned the value `"document-fonts"`.

However, `[@@bs.deriving jsConverter]` generates converter functions, which are also compiled and added to the JavaScript code. So the full compiled code is quite a bit:

```
var _map = {"Document_fonts":"document-fonts","Browser_fonts":"browser-fonts"};

var _revMap = {"document-fonts":"Document_fonts","browser-fonts":"Browser_fonts"};

function xToJs(param) {
  return _map[param];
}

function xFromJs(param) {
  return _revMap[param];
}

var b = xToJs("Document_fonts");

var a = "Document_fonts";

export {
  xToJs ,
  xFromJs ,
  a ,
  b ,
}
```

Things could be a lot cleaner:

1. The requirement of `[@@bs.deriving jsConverter]` attribute could be dropped, i.e., the definition of the polymorphic variant type, coupled with the `[@bs.as "x"]` attribute(s) should provide the intent adequately.
2. Ideally, i.e., from my understanding, the converter functions should not be needed and could be dropped too.
3. An assignment like
```
let a : x = `Document_fonts
```
for the above definition would ideally compile directly to
```
var a = "document-fonts";
```

**Comment by anmonteiro** [comment]
This isn't actually possible because we'd need to support defining polymorphic variants that break the OCaml syntax. i.e. it's not possible to write `type x = [`foo-bar]`

**Comment by anmonteiro** [comment]
this was done for regular variants in #884

**Comment by jbhoot** [comment]
Nice! Is this feature deployed to the playground? I tried it out [on the playground unsuccessfully](https://melange.re/v4.0.0/playground/?language=Reason&code=dHlwZSB0YW5zdGFja1RhYmxlU29ydE9yZGVyID0KICB8IFtAbWVsLmFzIGZhbHNlXSBGYWxzZQogIHwgW0BtZWwuYXMgImFzYyJdIEFzYwogIHwgW0BtZWwuYXMgImRlc2MiXSBEZXNjOwoKbGV0IG9yZGVyID0gQXNjOwoKbGV0IHNvcnRpbmdPcmRlciA9IHYgPT4KICBzd2l0Y2ggKHYpIHsKICB8IDAgPT4gRmFsc2UKICB8IDEgPT4gQXNjCiAgfCAyID0%2BIERlc2MKICB8IF8gPT4gRmFsc2UKICB9OwoKSnMuQ29uc29sZS5sb2coc29ydGluZ09yZGVyKDEpKTsK&live=off).

For a code block like

```
type tanstackTableSortOrder =
  | [@mel.as false] False
  | [@mel.as "asc"] Asc
  | [@mel.as "desc"] Desc;
```

the compiler warns:

```
Line 2, 6:
Alert: unused Unused attribute [@mel.as]
This means such annotation is not annotated properly.
For example, some annotations are only meaningful in externals
```

I checked out the PR you linked to. [One of the examples](https://github.com/melange-re/melange/blob/312f5a59522a3e475781d8752946e4bda9c1331f/test/blackbox-tests/mel-as-variants.t) there seem to be using similar syntax:

```
type t = Not_A [@mel.as "A"] | Not_B [@mel.as "B"] | Not_C
```

**Comment by anmonteiro** [comment]
as the example hints, the "regular variants as strings" feature isn't yet deployed to the playground
