### ISSUE TITLE
Uninterpreted extension 'bs.obj'

### ISSUE THREAD

**Issue by mobilemindtec** [melange-re/melange#667]
Hello,

I'm getting an error when compiling this file. I need a `default export {}` to be generated.

```rescript
[@mel.val] [@mel.scope ("process", "env")]
external node_env: string = "NODE_ENV";


let default = {
	"publicPath": node_env == "production" ? "/" : "/home/vue",
	"assetsDir": "./src/assets",
	"lintOnSave": false,	
	"devServer": {
		"host": "0.0.0.0",
		"port": "3000"
	}
}

```

```bash
└─$ dune build
File "vue_config.re", lines 5-13, characters 14-1:
 5 | ..............{
 6 |    "publicPath": node_env == "production" ? "/" : "/home/vue",
 7 |    "assetsDir": "./src/assets",
 8 |    "lintOnSave": false,
 9 |    "devServer": {
10 |            "host": "0.0.0.0",
11 |            "port": "3000"
12 |    }
13 | }
Error: Uninterpreted extension 'bs.obj'.
```

I tried to compile using `let john = {"name": "john", "age": 99};` as per the example on the site and got the same error. What am I doing wrong?

**Comment by anmonteiro** [comment]
Hey, a few things:
- looks like you’re using the main branch — any reason in particular? In that case you’ll also need this reason branch: https://github.com/reasonml/reason/pull/2721
- otherwise melange 1.0 + reason 3.9 should work as expected

**Comment by mobilemindtec** [comment]
Hi,

I had added the pin for the dev version months ago as soon as the project was announced and forgot to remove it. Using the official release worked. Thanks!

**Comment by anmonteiro** [comment]
Good to know. The next release will be breaking as per our [roadmap](https://anmonteiro.substack.com/p/whats-next-for-melange). We'll work on upgrade instructions and update the ecosystem too.
