### ISSUE TITLE
Dependency on `ocaml-migrate-parsetree`

### ISSUE THREAD

**Issue by pitag-ha** [melange-re/melange#671]
Hello :wave:

I'm not very familiar with the Melage ecosystem (yet). Is `mel` still the Melage build system? Does it still depend on OMP2? It does according to its [upstream opam file](https://github.com/ocaml/opam-repository/blob/master/packages/mel/mel.0.3.2/opam#L15), but I've neither found `mel` nor the OMP dependency here on the repo.

**Comment by anmonteiro** [comment]
Melange uses Dune since v1. The `mel` package was deleted an won't be released anymore.

We rely on ppxlib. Hope that helps.

**Comment by pitag-ha** [comment]
Perfect, thanks! Would it make sense to deprecate `mel` on opam?

**Comment by anmonteiro** [comment]
Sure, by making it unavailable, or?

**Comment by pitag-ha** [comment]
Oh, I didn't mean deleting the package from opam, no. I meant marking it as deprecated in the package's metadata, e.g. adding a `flags: deprecated` field to the upstream opam file or pointing out there in the synposis/description that it's deprecated. I don't think it's necessary, but I've mentioned it, because I might not be the only one coming across it on Opam and wondering about it.

I will close this issue, since it was about the OMP dependency question. Thanks again for the very quick answer!
