### ISSUE TITLE
Miscompilation of option eliminator when option type is defined through manifest

### ISSUE THREAD

**Issue by andreypopp** [melange-re/melange#691]
Consider this [snippet](https://melange.re/unstable/playground/?language=OCaml&code=bW9kdWxlIFggPSBzdHJ1Y3QKICB0eXBlICdhIHQgPSAnYSBvcHRpb24gPSBOb25lIHwgU29tZSBvZiAnYQplbmQKCmxldCAoKSA9IAogIG1hdGNoIFguTm9uZSB3aXRoCiAgfCBTb21lIF8gLT4gSnMubG9nICJBIEJVRyEiCiAgfCBOb25lIC0%2BIEpzLmxvZyAiT0si&live=off):
```
module X = struct
  type 'a t = 'a option = None | Some of 'a
end

let () = 
  match X.None with
  | Some _ -> Js.log "A BUG!"
  | None -> Js.log "OK"
```
which results in:
```
// Generated by Melange


var X = {};

console.log("A BUG!");

export {
  X ,
}
/*  Not a pure module */
```

Rescript [handles](https://rescript-lang.org/try?version=v10.1.2&code=LYewJgrgNgpgBADTgXjgbwFBzgFwJ4AO8AHgDwDkAhgHwpwgE4CWIAdhTXQHJvwA+cAMohgMABRUAlBgC+GDLBxwxkugGcA7kxwBjABaIAdD1bxMA4aLEB9VcloApNYaggA5mIBEAQTgAjCDdPaQETeHs4Jxd3LwB5AGlg2QwgA) this ok.

**Comment by anmonteiro** [comment]
This seems to be related to https://github.com/rescript-lang/rescript-compiler/pull/5174 and https://github.com/rescript-lang/rescript-compiler/issues/5169.
