### ISSUE TITLE
playground: include `melange.dom`

### ISSUE THREAD

**Issue by jchavarri** [melange-re/melange#707]
currently the playground bundle does not include `melange.dom`. I wonder if it should?

**Comment by anmonteiro** [comment]
I think it should be included, indeed.

**Comment by jchavarri** [comment]
I realized yesterday that we don't have a dom in the worker that executes code on the playground, so maybe not worth it... [example in v1 playground](https://melange.re/v1.0.0/playground/?language=OCaml&code=dHlwZSBkb2N1bWVudAoKZXh0ZXJuYWwgZG9jdW1lbnQgOiBkb2N1bWVudCA9ICJkb2N1bWVudCIgW0BAYnMudmFsXQpleHRlcm5hbCBnZXRfYnlfaWQgOiBkb2N1bWVudCAtPiBzdHJpbmcgLT4gRG9tLmVsZW1lbnQgPSAiZ2V0RWxlbWVudEJ5SWQiCiAgW0BAYnMuc2VuZF0KCmxldCBlbCA9IGdldF9ieV9pZCBkb2N1bWVudCAibXktaWQi&live=off) (where `Dom` is available).

**Comment by anmonteiro** [comment]
That's fair, but I think `melange.dom` will be a common enough addition to justify it. It'll make shareable snippets not error out.
