### ISSUE TITLE
Allow to export values with invalid OCaml names

### ISSUE THREAD

**Issue by jchavarri** [melange-re/melange#713]
At the moment, all values exported from the structure items of a module need to comply with OCaml `ident` [spec](https://v2.ocaml.org/manual/lex.html):

```
ident ::= (letter ∣ _) { letter ∣ 0…9 ∣ _ ∣ ' } 
```

But sometimes, it is useful to export ids with names starting with uppercase (like for [NextJS routes](https://nextjs.org/docs/app/building-your-application/routing/route-handlers)) or starting with numbers, etc.

In ReScript, this was solved at the parsing level allowing for [illegal identifiers](https://rescript-lang.org/docs/manual/latest/use-illegal-identifier-names) ([example](https://rescript-lang.org/try?code=PTAECUFMGUGMCcCWAHALtVBXAJpAdqgHTyQDOAUADaSqi4BmAhppbQLygBEAQgPYBGnckA})). A solution like this is probably not possible in Melange, as compatibility with Reason and OCaml parsers (or at least the latter) is required, but maybe a solution with PPX attributes is possible?

**Comment by anmonteiro** [comment]
This is very much desirable. I believe one of the options we chatted offline was to use `@mel.as`, e.g.:

``ocaml
let[@mel.as "POST"] post a b = a + 1

```
