### ISSUE TITLE
Figure out to deal with pipe first vs pipe last libraries

### ISSUE THREAD

**Issue by feihong** [melange-re/melange#731]
Right now we have the unfortunate situation where pipe last and pipe first modules are all together under `Js`, e.g. `Js.String` is pipe last and `Js.String2` is pipe first. We could add `Js.DataFirst` modules that allow you to use pipe first operators while the standard `Js` modules support pipe last operator as they always have. In your program you can specify your preference for pipe first by adding `open Js.DataFirst;` to the top of a source file or `-open Js.DataFirst` in dune file.

This is analagous to [StdLabels](https://melange.re/v1.0.0/api/re/melange/Stdlib/StdLabels/index.html) which allows you to easily swap out normal List functions with versions that use labeled arguments.

**Comment by jchavarri** [comment]
We discussed offline that maybe we can design the API in a way that is friendly for both pipe first and pipe last. We can do so by putting the `t` first and then using labels for the rest of the arguments. This is something that has worked already in the ecosystem (see [Tablecloth](tablecloth.dev) and [Jane Street's Base](https://opensource.janestreet.com/base/)).

As an example, instead of the current implementation of `Js.String.includes`:

https://github.com/melange-re/melange/blob/65d1702e21fed1a700e8eafdfcafa54d85758115/jscomp/runtime/js_string.ml#L196-L197

Or the one in `Js.String2.includes`:

https://github.com/melange-re/melange/blob/65d1702e21fed1a700e8eafdfcafa54d85758115/jscomp/runtime/js_string2.ml#L196-L197

We could do something like:

```ocaml
external includes : t -> substring:t -> bool = "includes" [@@mel.send]
```

That way, users of the library can decide how to use it:

```ocaml
let a = "Hello world" |> Js.String.includes ~substring:"Hello"
let b = "Hello world" |. Js.String.includes ~substring:"Hello"
```

**Comment by jchavarri** [comment]
One thing to consider about pipe last is that the generated code will be less performant. Consider this example:

```ocaml
type keycloak

external keycloak : keycloak = "default" [@@mel.module "keycloak-js"]

type initParam

external makeInitParam : onLoad:string -> unit -> initParam = "" [@@mel.obj]

type init

external init : keycloak -> param:initParam -> init = "init" [@@mel.send]

let one = keycloak |> init ~param:(makeInitParam ~onLoad:"login" ())
let two = keycloak |. init ~param:(makeInitParam ~onLoad:"login" ())
```

And the generated code for `one` and `two`:

```javascript
// Generated by Melange

import KeycloakJs from "keycloak-js";

var arg = {
  onLoad: "login"
};

var one = (function (param) {
      return param.init(arg);
    })(KeycloakJs);

var two = KeycloakJs.init({
      onLoad: "login"
    });

export {
  one ,
  two ,
}
/* one Not a pure module */
```

**Comment by EduardoRFS** [comment]
Hmmm the performance example is a lack of optimization. This inlining could potentially change the evaluation order, but for most cases(like this one) you can guarantee that this is not the case.

**Comment by johnhaley81** [comment]
@jchavarri the issue with the [performance example](https://github.com/melange-re/melange/issues/731#issuecomment-1752546335) is that it's mixing `@@mel.send` with pipe last. If you use `@@mel.send.pipe` both sides are optimized.

```ocaml
type keycloak

external keycloak : keycloak = "default" [@@mel.module "keycloak-js"]

type initParam

external makeInitParam : onLoad:string -> initParam = "" [@@mel.obj]

type init

external init : param:initParam -> init = "init" [@@mel.send.pipe: keycloak]

let one = keycloak |> init ~param:(makeInitParam ~onLoad:"login")
let two = keycloak |. init ~param:(makeInitParam ~onLoad:"login")

```

```javascript
// Generated by Melange

import KeycloakJs from "keycloak-js";

var one = KeycloakJs.init({
      onLoad: "login"
    });

var two = KeycloakJs.init({
      onLoad: "login"
    });

export {
  one ,
  two ,
}
/* one Not a pure module */
```

**Comment by anmonteiro** [comment]
I think this one has been fixed by the recent changes.
