### ISSUE TITLE
Allow [@mel.as ...] in constructors & record fields

### ISSUE THREAD

**Issue by hackwaly** [melange-re/melange#742]
https://rescript-lang.org/blog/improving-interop

**Comment by anmonteiro** [comment]
Doesnt this already work in v2?

can you provide an example that doesn’t work?

**Comment by hackwaly** [comment]
No, It doesn't.

<img width="580" alt="image" src="https://github.com/melange-re/melange/assets/540298/b722da92-157f-4f1a-96c2-9f66ce741ce1">

**Comment by anmonteiro** [comment]
Ah, I think we can make this work in variants.

FTR this already works for records (and inline records):

https://melange.re/v2.0.0/playground/?language=OCaml&code=dHlwZSB4ID0gewogIGE6IHN0cmluZyBbQG1lbC5hcyAib3RoZXIiXX0KbGV0IHggPSB7IGEgPSAiaGVsbG8iIH0%3D&live=off
