### ISSUE TITLE
Some warnings still reference bucklescript

### ISSUE THREAD

**Issue by jchavarri** [melange-re/melange#747]
https://github.com/melange-re/melange-compiler-libs/blob/eb8207c1b6744180095184194dfd843e06f9fad1/utils/warnings.ml#L566-L593

**Comment by davesnx** [comment]
This is a little confusing also (101) `"Unused bs attributes"`

**Comment by davesnx** [comment]
`bs` is present on warnings about this: https://melange.re/unstable/playground/?language=Reason&code=bGV0IHN1bSA9IChhLCBiKSA9PiB7CiAgYSArIGI7Cn07CgpsZXQgXyA9IHN1bSguIDQsIDUpOwo%3D&live=off
