### ISSUE TITLE
Doesn't export `external make` (before was used a bs.val)

### ISSUE THREAD

**Issue by davesnx** [melange-re/melange#748]
https://melange.re/unstable/playground/?language=Reason&code=LyoqCiAqIEltcG9ydGFudCBub3RlIG9uIHRoaXMgbW9kdWxlOgogKiBBcyBzb29uIGFzIFJlYWN0IHByb3ZpZGVzIGEgbWVjaGFuaXNtIGZvciBlcnJvci1jYXRjaGluZyB1c2luZyBmdW5jdGlvbmFsIGNvbXBvbmVudCwKICogdGhpcyBpcyBsaWtlbHkgdG8gYmUgZGVwcmVjYXRlZCBhbmQvb3IgbW92ZSB0byB1c2VyIHNwYWNlLgogKi8KCnR5cGUgaW5mbyA9IHtjb21wb25lbnRTdGFjazogc3RyaW5nfTsKCnR5cGUgcGFyYW1zKCdlcnJvcikgPSB7CiAgZXJyb3I6ICdlcnJvciwKICBpbmZvLAp9OwoKWyUlbWVsLnJhdwogIHt8CiAgdmFyIFJlYWN0ID0gcmVxdWlyZSgicmVhY3QiKTsKICB2YXIgRXJyb3JCb3VuZGFyeSA9IChmdW5jdGlvbiAoQ29tcG9uZW50KSB7CiAgICBmdW5jdGlvbiBFcnJvckJvdW5kYXJ5KHByb3BzKSB7CiAgICAgIENvbXBvbmVudC5jYWxsKHRoaXMpOwogICAgICB0aGlzLnN0YXRlID0ge2Vycm9yOiB1bmRlZmluZWR9OwogICAgfTsKICAgIEVycm9yQm91bmRhcnkucHJvdG90eXBlID0gT2JqZWN0LmNyZWF0ZShDb21wb25lbnQucHJvdG90eXBlKTsKICAgIEVycm9yQm91bmRhcnkucHJvdG90eXBlLmNvbXBvbmVudERpZENhdGNoID0gZnVuY3Rpb24oZXJyb3IsIGluZm8pIHsKICAgICAgdGhpcy5zZXRTdGF0ZSh7ZXJyb3I6IHtlcnJvcjogZXJyb3IsIGluZm86IGluZm99fSk7CiAgICB9OwogICAgRXJyb3JCb3VuZGFyeS5wcm90b3R5cGUucmVuZGVyID0gZnVuY3Rpb24oKSB7CiAgICAgIHJldHVybiB0aGlzLnN0YXRlLmVycm9yICE9IHVuZGVmaW5lZAogICAgICAgID8gdGhpcy5wcm9wcy5mYWxsYmFjayh0aGlzLnN0YXRlLmVycm9yKQogICAgICAgIDogdGhpcy5wcm9wcy5jaGlsZHJlbgogICAgfTsKICAgIHJldHVybiBFcnJvckJvdW5kYXJ5OwogIH0pKFJlYWN0LkNvbXBvbmVudCk7Cnx9Cl07CgpbQHJlYWN0LmNvbXBvbmVudF0KZXh0ZXJuYWwgbWFrZToKICAofmNoaWxkcmVuOiBSZWFjdC5lbGVtZW50LCB%2BZmFsbGJhY2s6IHBhcmFtcygnZXJyb3IpID0%2BIFJlYWN0LmVsZW1lbnQpID0%2BCiAgUmVhY3QuZWxlbWVudCA9CiAgIkVycm9yQm91bmRhcnkiOwo%3D&live=off

While before was generating a `var make = ErrorBoundary` in JavaScript

**Comment by davesnx** [comment]
While adding `let default = make;` in the precise case of ErrorBoundary generates broken code:

```
// errorBoundary.re
/**
 * Important note on this module:
 * As soon as React provides a mechanism for error-catching using functional component,
 * this is likely to be deprecated and/or move to user space.
 */

type info = {componentStack: string};

type params('error) = {
  error: 'error,
  info,
};

[%%mel.raw
  {|
  var React = require("react");
  var ErrorBoundary = (function (Component) {
    function ErrorBoundary(props) {
      Component.call(this);
      this.state = {error: undefined};
    };
    ErrorBoundary.prototype = Object.create(Component.prototype);
    ErrorBoundary.prototype.componentDidCatch = function(error, info) {
      this.setState({error: {error: error, info: info}});
    };
    ErrorBoundary.prototype.render = function() {
      return this.state.error != undefined
        ? this.props.fallback(this.state.error)
        : this.props.children
    };
    return ErrorBoundary;
  })(React.Component);
|}
];

module React = Types;

[@react.component]
external make:
  (~children: React.element, ~fallback: params('error) => React.element) =>
  React.element =
  "ErrorBoundary";

let default = make;
```

```
// React.re
module ErrorBoundary = ErrorBoundary;
```

```
// React.js
var React__ErrorBoundary = require("./errorBoundary.bs.js");

var ErrorBoundary = {
  make: ErrorBoundary
};


exports.ErrorBoundary = ErrorBoundary;

```

Which makes `React__ErrorBoundary` imported, but not referenced.

**Comment by anmonteiro** [comment]
This ended up being a local issue related to dangerous `%raw` use and javascript scoe.
