### ISSUE TITLE
exploration: Store external information in internal attributes

### ISSUE THREAD

**Issue by anmonteiro** [melange-re/melange#749]
Currently Melange external attributes store some internal marshaled data in the primitive payload, e.g.:

```ocaml
external document: t = "SOME_MARSHALED_DATA_GETS_INSERTED_HERE"
```

we want to explore storing that data in e.g. `[@internal.melange-external "PAYLOAD_HERE"]`

**Comment by jchavarri** [comment]
Related to https://github.com/melange-re/melange/issues/346.

**Comment by jchavarri** [comment]
Also related to #739.

**Comment by benbellick** [comment]
Hi! I opened up the above issue reasonml/reason-react#853, which I believe would be solved by this ticket. To repeat briefly, my editor is unable to handle the unexpected characters produced by the lsp when my cursor is over module definitions. I am using Emacs w/ Eglot. 

Alternatively, is there a different recommended developer experience for Emacs users?

**Comment by anmonteiro** [comment]
some work going on in #1222
