### ISSUE TITLE
Compiler conflates object types with `Js.t` object types

### ISSUE THREAD

**Issue by jchavarri** [melange-re/melange#758]
Not that the object part of the compiler is very used in Melange, but there seems to be some internal coercion that is unsafe.

```ocaml
class type node = {
  pub nodeName: string;
};
let node: node = {
  "nodeName": "div",
};

Js.log(node#nodeName)
```

Crashes at runtime: `Cannot read properties of undefined (reading '0')`.

**Comment by anmonteiro** [comment]
Interesting. This seems to be a regression since it's an error in the ReasonML playground: https://reasonml.github.io/en/try?rrjsx=true&reason=MYGwhgzhAEAuCeAHAptAdgewCaoLzQG8AoaaRAVwCN1tkA5MAW2QC5oJYAnASzQHMA3EQC+QkMlg0cbTDmj5ipAESz6TZErZKs3AG5KANCKFEAUhAB0IDHwAUqgMSqGzAJREgA

**Comment by jchavarri** [comment]
For completion, the issue affected not only object types, but any type, e.g. `Js.Obj.keys "foo"` would type check.
