### ISSUE TITLE
comments break mel.raw output

### ISSUE THREAD

**Issue by joprice** [melange-re/melange#763]
I'm unsure if this is expected, but comments in mel.raw expressions can cause parse errors at runtime. Code like the following:

```reason
[%mel.raw {|
// before
const a = 1;
// after
|}];
```

Generates the js:

```js
((// before
const a = 1;
// after));
```

And a parse error like the following:

```
Unexpected token (27:0)

      25 |
      26 | ((// before
    > 27 | const a = 1;
         | ^
      28 | // after
      29 | const b = 1;));
```

This works fine with `[%%mel.raw ...]`, since I assume it allows statements. Could this be caught earlier in the pipeline to avoid invalid generated code, or is this expected? If so, feel free to close and maybe this will help someone in the future who might be confused about the single and double percent sign for ocaml directives.

**Comment by anmonteiro** [comment]
I'm fixing this shortly. In the meantime, the workaround is a IIFE:

```ocaml
let () = [%mel.raw {|
(function() {
// before
const a = 1;
// after
})()
|}]
```

**Comment by anmonteiro** [comment]
> And a parse error like the following:

This is already caught earlier in the pipeline. In the current git HEAD, Melange emits the following warning:

```js
$ melc -ppx melppx x.ml
File "x.ml", line 20, characters 0-5:
Warning 103 [melange-ffi-warning]: FFI warning: Unexpected token `const`
// Generated by Melange
'use strict';


((// before
const a = 1;
// after));

/*  Not a pure module */
```
