### ISSUE TITLE
empty js object compilation

### ISSUE THREAD

**Issue by joprice** [melange-re/melange#780]
I was writing a test that calls an external that takes `Js.t` to allow passing js objects to mock a json endpoint, and wanted to test it with an empty object, but it compiled to something unexpected:

```reason
let body = {};
```

Output of `dune describe Tests.re.ml`:

```ocaml
...
 let body = object (this)  end in
...
```

Generated js:

```js
...
if (!object_tables.key) {
                              var $$class = CamlinternalOO.create_table(0);
                              var env = CamlinternalOO.new_variable($$class, "");
                              var env_init = function (env$1) {
                                var self = CamlinternalOO.create_object_opt(undefined, $$class);
                                self[env] = env$1;
                                return self;
                              };
                              CamlinternalOO.init_class($$class);
                              object_tables.key = env_init;
                            }
                            Curry._1(object_tables.key, undefined);
```

It seems that `mel.obj` is not inserted when using an empty object. Is there a way to write this external to call it with an empty object, so that the object is represented ?

```reason
[@mel.send.pipe: context] external json: Js.t({..}) => t = "json";
````

**Comment by davesnx** [comment]
That's an old issue from Reason (that I really really want to fix) https://github.com/reasonml/reason/issues/1667

**Comment by davesnx** [comment]
Maybe mel.obj should allow this `let emp = [%mel.obj {}];`?

**Comment by joprice** [comment]
Actually just noticed `Js.Obj.empty()`, which does the trick.

**Comment by anmonteiro** [comment]
I ran into this recently and also used `Js.Obj.empty()`.

**Comment by anmonteiro** [comment]
> Maybe mel.obj should allow this `let emp = [%mel.obj {}];`?

Empty records are a syntax error in OCaml.

**Comment by anmonteiro** [comment]
This also works:


```ocaml
(* x.ml *)
external the_obj : unit -> < > Js.t = "" [@@mel.obj]

let x : _ Js.t = the_obj ()
```

```shell
$ melc -ppx melppx x.ml
// Generated by Melange
'use strict';


var x = {};

exports.x = x;
/* No side effect */
```

**Comment by anmonteiro** [comment]
There isn't really anything actionable here for Melange. Closing in favor of https://github.com/reasonml/reason/issues/1667 tracked in the ReasonML repo.
