### ISSUE TITLE
playground: `ocaml.parseRE` takes 30s+ to process 4 lines of code

### ISSUE THREAD

**Issue by jchavarri** [melange-re/melange#808]
Given this input:

```reason
let foo = 42;   // int
let bar = 42.0; // float
Js.log(Js.typeof(foo)); // prints "number"
Js.log(Js.typeof(bar)); // prints "number"
```

The Reason parser built for the browser (called through `ocaml.parseRE`) will take more than 30s to produce the resulting AST.

I am not able to reproduce when calling `refmt` natively.

Here's a cram test, I am not opening a PR as I am not sure how to test this and I don't want to slow down the tests:

```
  $ cat > input.js <<\EOF
  > require(process.env.DUNE_SOURCEROOT + '/_build/default/bin/jsoo_main.bc.js');
  > require(process.env.DUNE_SOURCEROOT + '/_build/default/bin/melange-cmijs.js');
  > try { console.log(ocaml.parseRE(`let foo = 42;   // int
  > let bar = 42.0; // float
  > Js.log(Js.typeof(foo)); // prints "number"
  > Js.log(Js.typeof(bar)); // prints "number"`)) } catch (e) { console.log(e); };
  > EOF

  $ time node input.js
  [
    0,
    [ 0, [ 0, [Array], [Array] ], [ 0, [Array], [Array] ] ],
    [ 0, [ 0, [Array], 0, ' int\n' ], [ 0, [Array], [Array] ] ]
  ]
  34.74user 0.27system 0:34.91elapsed 100%CPU (0avgtext+0avgdata 251600maxresident)k
  0inputs+8outputs (0major+184940minor)pagefaults 0swaps
```

Reported by @feihong (we originally thought the playground had frozen, it turned out it was just taking a long time to respond).

**Comment by feihong** [comment]
Here is an even shorter program to reproduce it: 

```reason
//Js.log(1)
```
[Playground link](https://melange.re/v2.1.0/playground/?language=Reason&code=Ly9Kcy5sb2coMSk%3D&live=off
)

An alternate way to trigger it is to put `Js.log(1)` in the code editor, then manually comment it out. On Firefox it will freeze immediately and then recover in about a minute. On Chrome it will usually behave the same but not consistently. It seems this performance regression is triggered whenever the last thing in the AST is a `//` comment.
