### ISSUE TITLE
Melange could remove the `[@mel.inline]` in favor of a bind to the cases it matters

### ISSUE THREAD

**Issue by davesnx** [melange-re/melange#835]
Instead of providing a way to inline stuff (and being the recommended way of doing it), maybe would be nice to provide a binding to `Process.env` that gets inlined automatically? There are other cases like this matters?

https://melange.re/unstable/playground/?language=Reason&code=W0BtZWwuc2NvcGUgKCJwcm9jZXNzIiwgImVudiIpXSBleHRlcm5hbCBub2RlX2Vudjogc3RyaW5nID0gIk5PREVfRU5WIjsKCmxldCBkZXZlbG9wbWVudCA9ICJkZXZlbG9wbWVudCI7CmxldCAoKSA9CiAgaWYgKG5vZGVfZW52ICE9IGRldmVsb3BtZW50KSB7CiAgICBKcy5sb2coIk9ubHkgaW4gUHJvZHVjdGlvbiIpOwogIH07CgpbQG1lbC5pbmxpbmVdCmxldCBkZXZlbG9wbWVudF9pbmxpbmUgPSAiZGV2ZWxvcG1lbnQiOwpsZXQgKCkgPQogIGlmIChub2RlX2VudiAhPSBkZXZlbG9wbWVudF9pbmxpbmUpIHsKICAgIEpzLmxvZygiT25seSBpbiBQcm9kdWN0aW9uIik7CiAgfTsK&live=off

**Comment by anmonteiro** [comment]
Yeah, `process.env` is a bit specific. For example, the initial use case for that feature was React Native iOS / Android https://github.com/rescript-lang/rescript-compiler/issues/3472

**Comment by davesnx** [comment]
Right both cases are very specific. Maybe not much we can do rather than explaining it as a rare case and link to the particular issues.
