### ISSUE TITLE
Gentype + in-source builds

### ISSUE THREAD

**Issue by anmonteiro** [melange-re/melange#84]
Right now we don't generate dune `(promote ..)` rules for gentype files. 

This is not as easy as in-source compilation of `.ml` / `.re` / `.res` files: these _always_ generate a `.bs.js` file, whereas to know which files generate a `.gen.tsx` we'll have to read attributes in the parsetree.

**Comment by anmonteiro** [comment]
This is outdated. It can likely be fixed with dune rules.

**Comment by idfunctor** [comment]
@anmonteiro sorry if spammy, but I am desperately trying to have in-source build + genType (to emit TypeScript types) in Reason. Context is that I want to switch an new ReScript project to Reason, and can't go ahead until I can replicate how ReScript easily emits the TS code. Would appreciate some direction! thanks!
