### ISSUE TITLE
RFC: enabling `generators` by default 

### ISSUE THREAD

**Issue by anmonteiro** [melange-re/melange#87]
### Context

- Melange inherited ReScript's behavior that generators don't get run for dependencies
- Generators are much more useful in Melange because:
  1. it's easier to consume native dependencies
  2. `bsb` is effectively a frontend to Dune, and Dune can do the job of tracking dependencies between these rules

### Proposal

- Preserve the current behavior of disabling generators when `cut-generators` is `true` in `bsconfig.json`
- If not specified, even for dependencies, default to running the generator rules.

### Tradeoffs

- 👎  Some builds might get slower if they rely on expensive generators or have many of such rules
  - 👍 There's always `cut-generators: false` for these cases
- 👍 We move a few steps away from the culture of checking in generated code, deferring more responsibility to the build system

**Comment by jchavarri** [comment]
I stumbled upon this issue today while trying to configure an app to depend on a lib that uses generators to produce ml files from atd sources.

Here's a small repro using Yarn workspaces + atdgen that might be useful for testing.

The errors are of the kind of `Error: No rule found for node_modules/my_lib/textFilter_t.ml`. Which I assume make sense if generators are not run upstream.

[error_generators_lib.zip](https://github.com/melange-re/melange/files/6238119/error_generators_lib.zip)
