### ISSUE TITLE
mel.as inside polyvariants should warn about not using mel.string

### ISSUE THREAD

**Issue by davesnx** [melange-re/melange#877]
Combine mel.as in more places is indeed interesting, since would allow to idiomatically bind to JS with 0 cost.

An example of lowercasing them (a silly example)
```
external foo: (~arg: [ | [@mel.as "lola"] `Lola | [@mel.as "flores"] `Flores]) => unit = "asdf";

let _ = foo(~arg=`Lola);
```

**Comment by davesnx** [comment]
Silly me, adding `[@mel.string]` works with this case.

```
external foo:
  (
    ~arg: [@mel.string] [ | [@mel.as "lola"] `Lola | [@mel.as "flores"] `Flores]
  ) =>
  unit =
  "asdf";

let _ = foo(~arg=`Lola);
```

My first code should have alerted me to add mel.string.

**Comment by anmonteiro** [comment]
> My first code should have alerted me to add mel.string.

It works without `@mel.string` since #722 

```shell
$ melc -ppx melppx  x.ml
// Generated by Melange
'use strict';


asdf("lola");

/*  Not a pure module */
```
