### ISSUE TITLE
Add support to `-format` from AST

### ISSUE THREAD

**Issue by EduardoRFS** [melange-re/melange#88]
This feature is particularly useful when working with ppx, source:

https://github.com/melange-re/melange/pull/86#discussion_r603153802

**Comment by anmonteiro** [comment]
This is a good first issue, and very similar to #86. In short, if we get an ast file (let's define `.ast` and `.iast` extensions for implementation an interface, respectively), we can avoid the parsing step and simply print it.

**Comment by laaksonel** [comment]
Is this something as simple as
```ocaml
  | Impl_ast ->
    let ast = Binary_ast.read_ast_exn ~fname:input Ml setup_error_printer in
    impl_format_fn ~comments:(`Re []) ast
  | Intf_ast ->
    let ast = Binary_ast.read_ast_exn ~fname:input Mli setup_error_printer in
    intf_format_fn ~comments:(`Re []) ast
```

**Comment by anmonteiro** [comment]
We don't support formatting in the compiler anymore. This is best done by other tooling.
