### ISSUE TITLE
dev / production configuration

### ISSUE THREAD

**Issue by anmonteiro** [melange-re/melange#92]
sort of the same as https://github.com/rescript-lang/rescript-compiler/issues/3716

this needs more thinking but I'm opening this so I don't forget

**Comment by EduardoRFS** [comment]
can we register it on dune to run the rules based on the profile? So `(if profile == dev)` we add `-bs-g`

**Comment by anmonteiro** [comment]
The plan is for melange to be tightly integrated into dune. As such, we'll get [dune profiles](https://dune.readthedocs.io/en/stable/dune-files.html#profile) for free.
