### ISSUE TITLE
OCaml 5.1.1 support

### ISSUE THREAD

**Issue by kit-ty-kate** [melange-re/melange#922]
https://discuss.ocaml.org/t/ocaml-5-1-1-incoming-breaking-change-in-the-marshal-module/13457

Melange is one of the very few packages affected by this.

**Comment by anmonteiro** [comment]
Absolutely. We're eager to upgrade as soon as the new version is out.

**Comment by kit-ty-kate** [comment]
btw you can test it locally using `opam switch create 5.1.1+trunk`

**Comment by anmonteiro** [comment]
I opened #926 but the tests are failing because we need the uncompressed artifacts. do you know how to pass `--without-zstd` to the OCaml compiler configure phase?

**Comment by anmonteiro** [comment]
I suppose this is the solution but I'm not sure https://github.com/ocaml/opam-repository/pull/24845

I also don't know how to test it here without the opam-repository PR having been merged. Is there a way?

**Comment by kit-ty-kate** [comment]
> I also don't know how to test it here without the opam-repository PR having been merged. Is there a way?

https://github.com/melange-re/melange/pull/926/files#r1405265994 should be enough i believe

**Comment by kit-ty-kate** [comment]
5.1.1~rc1 has been released. Could we get a release of melange?
