### ISSUE TITLE
Don't generate .merlin files

### ISSUE THREAD

**Issue by jchavarri** [melange-re/melange#95]
Are `.merlin` files needed, now that merlin queries Dune directly? 
https://github.com/ocaml/merlin/pull/1123

**Comment by anmonteiro** [comment]
I tried not generating them and couldn't get it working, but I'll investigate why next time 🙂

**Comment by anmonteiro** [comment]
I just tried this again and the `.merlin` file seems to be necessary. I'll leave this issue open, however, to investigate how we can integrate with `dot-merlin-reader` for a more seamless dune integration.

**Comment by anmonteiro** [comment]
I think this will only be possible when we have builtin-support in Dune

**Comment by anmonteiro** [comment]
There's `"generate-merlin": false` that you can add to `bsconfig.json`. Dune support will bring the ability to not need merlin files, but that's not our concern to track here. Closing.
